"use client";

import { useEffect, useMemo, useState } from "react";
import { groupInspectionRows, matchCohort, recurrenceAnalysis, timelineAnalysis, type ClosureEpisode, type CohortFilters, type InspectionEvent, type RawInspectionRow } from "../lib/closure-analysis";
import type { BoroughMapPath } from "../lib/inspections";
import { BookChapters } from "./BookChapters";
import { SampleLauncher } from "./SampleLauncher";

const fmt=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"});
type FetchState="idle"|"loading"|"success"|"fallback";
type MatchTier="exact"|"strong"|"broad";
type ClosureMode="first"|"repeat";
function buildComparison(selected:ClosureEpisode,episodes:ClosureEpisode[],filters:CohortFilters,tier:MatchTier){const selectedCodes=new Set(selected.closure.codes.map(c=>c.code));const criticalCodes=selected.closure.codes.filter(c=>c.critical).map(c=>c.code);const strongMinimum=Math.max(2,Math.ceil(selectedCodes.size*2/3));const broadMinimum=Math.max(2,Math.ceil(selectedCodes.size/2));return matchCohort(selected,episodes,{...filters,minSharedCodes:0}).filter(e=>{const episodeCodes=new Set(e.closure.codes.map(c=>c.code));const overlap=[...selectedCodes].filter(code=>episodeCodes.has(code)).length;if(tier==="exact")return overlap===selectedCodes.size&&episodeCodes.size===selectedCodes.size;if(tier==="strong")return overlap>=strongMinimum&&criticalCodes.every(code=>episodeCodes.has(code));return overlap>=broadMinimum})}
function recommendedTier(selected:ClosureEpisode,episodes:ClosureEpisode[],filters:CohortFilters):MatchTier{if(buildComparison(selected,episodes,filters,"exact").length)return"exact";if(buildComparison(selected,episodes,filters,"strong").length)return"strong";return"broad"}

export function ConnectedJourney({episodes,events,boroughMap,fetchedAt}:{episodes:ClosureEpisode[];events:InspectionEvent[];boroughMap:BoroughMapPath[];fetchedAt:string}){
  const sample=useMemo(()=>episodes.find(e=>e.closure.codes.length>=2&&buildComparison(e,episodes,{scope:"city",burdenTolerance:99,periodYears:2,inspectionType:true,minSharedCodes:0},"exact").length>=2)??episodes.find(e=>e.reopening&&e.closure.codes.length>=3)??episodes[0],[episodes]);
  const [selected,setSelected]=useState<ClosureEpisode|null>(null);
  const [query,setQuery]=useState("");
  const [filters,setFilters]=useState<CohortFilters>({scope:"borough",burdenTolerance:2,periodYears:2,inspectionType:true,minSharedCodes:1});
  const [selectedCodes,setSelectedCodes]=useState<string[]>([]);
  const [matchTier,setMatchTier]=useState<MatchTier>("exact");
  const [lockedIds,setLockedIds]=useState<string[]>([]);
  const [latest,setLatest]=useState<InspectionEvent[]>([]);
  const [fetchState,setFetchState]=useState<FetchState>("idle");
  const [peerSaved,setPeerSaved]=useState(false);
  const [patternTab,setPatternTab]=useState<"absent"|"remained"|"appeared">("remained");
  const [closureMode,setClosureMode]=useState<ClosureMode|null>(null);
  const matches=useMemo(()=>{const q=query.trim().toLowerCase();return q.length<2?[]:episodes.filter(e=>`${e.name} ${e.camis} ${e.borough} ${e.zipcode}`.toLowerCase().includes(q)).slice(0,7)},[episodes,query]);
  const activeCodes=selectedCodes.length?selectedCodes:selected?.closure.codes.map(c=>c.code)??[];
  const draftCohort=useMemo(()=>selected?buildComparison(selected,episodes,filters,"exact"):[],[selected,episodes,filters]);
  const cohort=useMemo(()=>{const ids=new Set(lockedIds);return episodes.filter(e=>ids.has(e.id))},[episodes,lockedIds]);
  const cohortDirty=useMemo(()=>draftCohort.map(e=>e.id).sort().join("|")!==[...lockedIds].sort().join("|"),[draftCohort,lockedIds]);
  const transitions=useMemo(()=>transitionRows(cohort),[cohort]);
  const recurrence=useMemo(()=>recurrenceAnalysis(cohort,fetchedAt.slice(0,10)),[cohort,fetchedAt]);
  const timeline=useMemo(()=>timelineAnalysis(cohort,fetchedAt.slice(0,10)),[cohort,fetchedAt]);
  const timingBuckets=useMemo(()=>[["0–3 days",0,3],["4–7 days",4,7],["8–14 days",8,14],["15–30 days",15,30],["31+ days",31,Infinity]] as const,[]);
  const commonTimingRange=useMemo(()=>timeline.values.length?[...timingBuckets].map(([label,min,max])=>({label,count:timeline.values.filter(value=>value>=min&&value<=max).length})).sort((a,b)=>b.count-a.count)[0]:null,[timeline.values,timingBuckets]);
  const latestRecords=useMemo(()=>{const source=fetchState==="success"?latest:events;if(!selected)return[];const records=source.filter(e=>e.camis===selected.camis).sort((a,b)=>b.date.localeCompare(a.date)||a.action.localeCompare(b.action)||a.id.localeCompare(b.id));const newestDate=records[0]?.date;return records.filter(e=>e.date===newestDate)},[events,fetchState,latest,selected]);
  const priorEpisodes=useMemo(()=>selected?episodes.filter(e=>e.camis===selected.camis&&e.closure.date<selected.closure.date).sort((a,b)=>b.closure.date.localeCompare(a.closure.date)):[],[episodes,selected]);
  const previousEpisode=priorEpisodes[0]??null;

  useEffect(()=>{if(!selected)return;let cancelled=false;const params=new URLSearchParams({"$select":"camis,dba,boro,building,street,zipcode,inspection_date,inspection_type,action,violation_code,violation_description,critical_flag,score,grade,grade_date,record_date,latitude,longitude","$where":`camis='${selected.camis}'`,"$order":"inspection_date DESC","$limit":"50000"});fetch(`https://data.cityofnewyork.us/resource/43nn-pn8j.json?${params}`).then(r=>{if(!r.ok)throw new Error("request failed");return r.json()}).then((rows:RawInspectionRow[])=>{if(!cancelled){setLatest(groupInspectionRows(rows));setFetchState("success")}}).catch(()=>{if(!cancelled)setFetchState("fallback")});return()=>{cancelled=true}},[selected]);
  useEffect(()=>{const reset=()=>{setSelected(null);setQuery("");setSelectedCodes([]);setFilters({scope:"borough",burdenTolerance:2,periodYears:2,inspectionType:true,minSharedCodes:1});setMatchTier("exact");setLockedIds([]);setLatest([]);setFetchState("idle");setPeerSaved(false);setPatternTab("remained");setClosureMode(null)};window.addEventListener("six-days-reset",reset);return()=>window.removeEventListener("six-days-reset",reset)},[]);
  useEffect(()=>{if(!sample)return;const load=()=>{const next={...filters,scope:"city" as const,boroughOverride:undefined,burdenTolerance:99};const hasPrior=episodes.some(e=>e.camis===sample.camis&&e.closure.date<sample.closure.date);setSelected(sample);setClosureMode(hasPrior?"repeat":"first");setQuery(sample.name);setSelectedCodes(sample.closure.codes.map(code=>code.code));setFilters(next);setLockedIds([]);setLatest([]);setFetchState("loading")};window.addEventListener("six-days-load-sample",load);return()=>window.removeEventListener("six-days-load-sample",load)},[sample,filters,episodes]);
  const choose=(episode:ClosureEpisode)=>{const next={...filters,scope:"city" as const,boroughOverride:undefined,burdenTolerance:99};const hasPrior=episodes.some(e=>e.camis===episode.camis&&e.closure.date<episode.closure.date);setSelected(episode);setClosureMode(hasPrior?"repeat":"first");setQuery(episode.name);setSelectedCodes(episode.closure.codes.map(code=>code.code));setFilters(next);setLockedIds([]);setLatest([]);setFetchState("loading")};

  const unlockedThrough = !selected ? 1 : cohort.length ? 5 : 2;
  const timingPage=<section className="book-chapter owner-step timeline-step" id="timeline"><Step n="03" title="Understand the historical timeline" question="How long did exact-match restaurants take to reopen?"/><p className="step-intro">This timeline uses only the exact violation-set benchmark saved in Step 2.</p><Impact>Use the historical range to estimate how long your business may need financial and operational coverage—not as a promised reopening date.</Impact>{selected&&cohort.length?<><section className="timeline-answer" aria-label="Primary reopening-time result"><span>TYPICAL RECORDED REOPENING TIME</span><div><strong>{timeline.median??"—"}</strong><b>days</b></div><p>Based on {timeline.matched} of {timeline.total} exact-match closure records with a later reopening recorded.</p></section><div className="timeline-summary"><article><span>FAST CASES</span><strong>{timeline.values.filter(value=>value<=3).length} of {timeline.matched}</strong><p>received a reopening record within 3 days</p></article><article><span>MOST COMMON RANGE</span><strong>{commonTimingRange?.label??"Not available"}</strong><p>{commonTimingRange?`${commonTimingRange.count} of ${timeline.matched} recorded reopenings fell here`:"No reopening intervals were available"}</p></article><article><span>LONGER CASES</span><strong>{timeline.thresholds.find(item=>item.days===14)?.without??0}</strong><p>eligible cases had no reopening recorded by day 14</p></article></div><div className="timeline-evidence"><h3>Where the recorded reopenings occurred</h3><p>Each bar shows the share of exact-match cases with a later reopening record.</p><TimelineBars values={timeline.values}/></div><section className="delay-checkpoints"><div><span>PLANNING CHECKPOINTS</span><h3>Some cases remained unresolved longer</h3><p>These percentages include every exact-match closure old enough to measure at each checkpoint.</p></div><div className="delay-grid">{timeline.thresholds.map(item=><article key={item.days}>{item.eligible?<><span>NO REOPENING BY DAY {item.days}</span><strong>{item.rate.toFixed(1)}%</strong><p>{item.without} of {item.eligible} eligible cases</p></>:<><span>DAY {item.days}</span><strong>—</strong><p>Not enough cases old enough to measure</p></>}</article>)}</div></section><p className="plain-note"><strong>What this means:</strong> plan for more than one timing scenario. These are historical public-record intervals, not a prediction for {selected.name}.</p></>:<EmptyState/>}</section>;
  const selectedCodeSet=new Set(activeCodes);
  const ownTransitionRows=transitions.rows.filter(row=>selectedCodeSet.has(row.code));
  const ownRecurrence={...recurrence,codes:recurrence.codes.filter(row=>selectedCodeSet.has(row.code))};
  const patternPage=<section className="book-chapter owner-step" id="change"><Step n="04" title="Prioritize the recorded patterns" question="What happened to my violations in later public records?"/><p className="step-intro">Follow every violation from the exact-match benchmark into the restaurants’ next recorded reopening and, where observable, a later closure.</p><Impact>Shows which codes were absent or still recorded so the owner knows which documented areas merit closer discussion with DOHMH or a qualified adviser.</Impact>{selected&&cohort.length?<><div className="pattern-evidence-base"><article><span>EXACT-MATCH CLOSURES</span><strong>{cohort.length}</strong><p>saved from Step 2</p></article><i aria-hidden="true">→</i><article><span>REOPENING RECORDS</span><strong>{transitions.eligible}</strong><p>available for change analysis</p></article><i aria-hidden="true">→</i><article><span>LATER CLOSURES</span><strong>{recurrence.reclosed}</strong><p>available for recurrence analysis</p></article></div><ViolationOutcomeTable selected={selected} rows={ownTransitionRows} recurrence={ownRecurrence}/><details className="comparison-details secondary-patterns"><summary>See other codes first recorded at reopening <span>+</span></summary><div className="change-grid single"><TransitionList title="Other codes newly recorded" rows={transitions.rows.filter(row=>!selectedCodeSet.has(row.code)&&row.appeared>0).sort((a,b)=>b.appeared-a.appeared).slice(0,8)} value={row=>`${row.appeared} of ${transitions.eligible} · ${percent(row.appeared,transitions.eligible)}`}/></div></details><p className="plain-note">These patterns organize public evidence. They do not prove a repair was incomplete, identify a required service, or predict another closure.</p></>:<EmptyState/>}</section>;

  return <BookChapters unlockedThrough={unlockedThrough}>
    <header className="book-chapter new-hero journey-landing" id="top"><div className="hero-mark" aria-hidden="true">6</div><div className="hero-content"><p className="live-label"><i/> NYC violation evidence + timing benchmarks</p><p className="hero-overline">One journey. Two closure contexts.</p><h1>First closure<br/>or <em>closed again?</em></h1><p>Six Days checks the available public history, adapts the evidence to your closure context, and keeps one shared path from official record to manager summary.</p><div className="hero-actions-row"><button type="button" className="start-button" onClick={()=>window.dispatchEvent(new CustomEvent("six-days-go-step",{detail:"find"}))}>Find my restaurant <span>→</span></button><SampleLauncher /></div></div><div className="hero-proof"><strong>Closure history check</strong><span>Exact violation-set benchmark</span><span>First or repeat analysis</span><small>Owner confirmation required</small></div></header>
    <section className="book-chapter owner-step" id="find"><Step n="01" title="Confirm my closure" question="Is this my first recorded closure—or has NYC closed this restaurant before?"/><p className="step-intro">Begin with the official public record. Six Days checks earlier closure episodes for the same CAMIS, then asks you to confirm how to review the selected event.</p><Impact>Separates first-closure orientation from repeat-closure pattern review without creating two different products.</Impact><div className="finder"><label htmlFor="restaurant-search">Restaurant name or CAMIS number</label><div className="search-row"><input id="restaurant-search" value={query} onChange={e=>{setQuery(e.target.value);setSelected(null);setClosureMode(null)}} placeholder="Start typing a restaurant name…"/><span>NYC OPEN DATA</span></div>{matches.length>0&&!selected&&<ul className="search-results">{matches.map(e=><li key={e.id}><button onClick={()=>choose(e)}><strong>{e.name}</strong><span>{e.borough} · closed {e.closure.date} · CAMIS {e.camis}</span></button></li>)}</ul>}{selected&&<><ClosureCard episode={selected}/><ClosureContext mode={closureMode??"first"} priorEpisodes={priorEpisodes} onChange={setClosureMode}/></>}</div></section>

    <section className="book-chapter owner-step context-step" id="compare">
      <Step n="02" title={closureMode==="repeat"?"Compare this closure":"Build my comparison"} question={closureMode==="repeat"?"What changed since the previous recorded closure?":`How does ${selected?.name??"my restaurant"} compare with restaurants closed for the same violations?`}/>
      <p className="step-intro">{closureMode==="repeat"?"Start with the restaurant’s own earlier closure, then place the current event inside the same exact-match benchmark used for first closures.":"Six Days searches NYC closure records for restaurants with the exact same set of recorded violation codes, then combines those matches into one transparent benchmark profile."}</p>
      <Impact>{closureMode==="repeat"?"Shows which recorded codes returned, disappeared, or appeared for the first time before comparing the current closure with like-for-like public records.":"Shows how the selected closure compares with genuinely like-for-like public records before using their reopening history for planning."}</Impact>
      {selected?<>
        {closureMode==="repeat"&&previousEpisode&&<RepeatClosureComparison current={selected} previous={previousEpisode} priorCount={priorEpisodes.length}/>}
        <ExactBenchmark selected={selected} matches={draftCohort}/>
        {draftCohort.length>0&&<PeerSetMap paths={boroughMap} episodes={draftCohort}/>}
        <button type="button" className={`use-peer-set ${peerSaved?"saved":""}`} disabled={!draftCohort.length||peerSaved} onClick={()=>{setLockedIds(draftCohort.map(e=>e.id));setPeerSaved(true);window.setTimeout(()=>{window.dispatchEvent(new CustomEvent("six-days-go-step",{detail:"timeline"}));setPeerSaved(false)},550)}}>{peerSaved?"Exact benchmark saved":"Use this exact-match benchmark"}<span>{peerSaved?"✓":"→"}</span></button><p className="peer-save-status" aria-live="polite">{peerSaved?"Benchmark saved. Opening timing…":""}</p>
        <details className="comparison-details"><summary>Change geographic scope <span>+</span></summary><div className="comparison-builder"><label><span>Geographic scope</span><select value={filters.scope==="city"?"city":filters.boroughOverride||selected.borough} onChange={e=>{const next={...filters,scope:e.target.value==="city"?"city" as const:"borough" as const,boroughOverride:e.target.value==="city"?undefined:e.target.value};setFilters(next);setLockedIds([])}}><option value="city">All NYC boroughs</option>{["Bronx","Brooklyn","Manhattan","Queens","Staten Island"].map(b=><option key={b} value={b}>{b}</option>)}</select></label></div><aside className="dataset-boundary"><strong>Public-record boundary</strong><p>Sharing one violation code does not prove that two businesses had equivalent conditions, severity, repairs, or outcomes.</p></aside></details>
      </>:<EmptyState/>}
    </section>

    {timingPage}
    {patternPage}

    <section className="book-chapter owner-step monitor-step" id="monitor"><Step n="05" title="Review my manager summary" question="What does the evidence mean for my next decisions?"/><p className="step-intro">Bring the selected closure, peer timing, restaurant-specific recorded patterns, and newest public record together in one view.</p><Impact>Gives the owner a concise evidence summary for planning and for the next conversation with DOHMH or a qualified adviser.</Impact>{selected?<><ManagerSummary selected={selected} cohort={cohort} timeline={timeline} transitions={ownTransitionRows} recurrence={ownRecurrence} mode={closureMode??"first"} previous={previousEpisode}/><FetchStateLabel state={fetchState} fetchedAt={fetchedAt}/><LatestRecord closure={selected.closure} latest={latestRecords}/><div className="final-boundary"><strong>Six Days informs. The owner decides.</strong><p>This is a public-data snapshot, not continuous monitoring, legal operating status, a corrective-action checklist, or confirmation of reopening. Only NYC DOHMH authorizes reopening.</p></div></>:<EmptyState/>}</section>
  </BookChapters>
}

function Step({n,title,question}:{n:string;title:string;question:string}){return <><div className="step-label"><span>STEP {n}</span><i>{title}</i></div><h2>{question}</h2></>}
function Impact({children}:{children:React.ReactNode}){return <p className="business-impact"><strong>Business impact</strong>{children}</p>}
function EmptyState(){return <p className="journey-empty">Choose a restaurant in Step 1 to calculate this section.</p>}
function ExactBenchmark({selected,matches}:{selected:ClosureEpisode;matches:ClosureEpisode[]}){const median=(values:number[])=>{const sorted=[...values].sort((a,b)=>a-b);return sorted.length?(sorted.length%2?sorted[(sorted.length-1)/2]:(sorted[sorted.length/2-1]+sorted[sorted.length/2])/2):null};const critical=(episode:ClosureEpisode)=>episode.closure.codes.filter(code=>code.critical).length;const reopened=matches.filter(item=>item.reopening).length;const medianScore=median(matches.flatMap(item=>item.closure.score===null?[]:[item.closure.score]));const medianDays=median(matches.flatMap(item=>item.reopeningDays===null?[]:[item.reopeningDays]));return <section className="exact-benchmark" aria-label="Selected restaurant compared with exact violation-set benchmark"><header><span>EXACT VIOLATION-SET CHECK</span><strong>{matches.length?`${matches.length} matching closure ${matches.length===1?"record":"records"} found`:`No exact match found`}</strong><p>{matches.length?`Every benchmark record contains exactly ${selected.closure.codes.length} codes—the same set recorded for ${selected.name}.`:`No other qualifying closure in the selected area, inspection type, and two-year period contains this exact ${selected.closure.codes.length}-code set.`}</p></header><div className="benchmark-columns"><article><span>YOUR RESTAURANT</span><h3>{selected.name}</h3><dl><div><dt>Violation codes</dt><dd>{selected.closure.codes.map(code=>code.code).join(", ")}</dd></div><div><dt>Critical flags</dt><dd>{critical(selected)}</dd></div><div><dt>Inspection score</dt><dd>{selected.closure.score??"Not recorded"}</dd></div><div><dt>Recorded outcome</dt><dd>{selected.reopening?`${selected.reopeningDays} days to reopening record`:"No reopening matched"}</dd></div></dl></article><article className="benchmark-profile"><span>COMPARABLE PROFILE · AGGREGATED</span><h3>{matches.length?`${new Set(matches.map(item=>item.camis)).size} comparable restaurants`:"Exact benchmark unavailable"}</h3>{matches.length?<dl><div><dt>Violation codes</dt><dd>{selected.closure.codes.map(code=>code.code).join(", ")}</dd></div><div><dt>Typical critical flags</dt><dd>{median(matches.map(critical))}</dd></div><div><dt>Median inspection score</dt><dd>{medianScore??"Not recorded"}</dd></div><div><dt>Reopening recorded</dt><dd>{reopened} of {matches.length} · {percent(reopened,matches.length)}</dd></div><div><dt>Median recorded interval</dt><dd>{medianDays===null?"Not available":`${medianDays} days`}</dd></div></dl>:<p className="benchmark-no-match">The app does not silently substitute weaker matches. Change the geographic scope or return to Step 1 to test another restaurant.</p>}</article></div><footer>This comparable profile is a benchmark calculated from matched public records—not a real or “average” restaurant.</footer></section>}
function ViolationOutcomeTable({selected,rows,recurrence}:{selected:ClosureEpisode;rows:TransitionRow[];recurrence:ReturnType<typeof recurrenceAnalysis>}){const rowMap=new Map(rows.map(row=>[row.code,row]));const recurrenceMap=new Map(recurrence.codes.map(row=>[row.code,row.count]));const measured=selected.closure.codes.filter(code=>(rowMap.get(code.code)?.atClosure??0)>0);const absentInAll=measured.filter(code=>{const row=rowMap.get(code.code)!;return row.absent===row.atClosure}).length;return <section className="violation-outcomes organized" aria-label="Later public-record patterns for every selected violation"><header><span>REOPENING CHANGE</span><h3>{measured.length?`${absentInAll} of ${measured.length} violations were absent from every available reopening record`:`No reopening record was available for comparison`}</h3><p>“Absent” means a code did not appear in the next matched reopening record. It does not establish why the restaurant reopened.</p></header><div className="outcome-code-list">{selected.closure.codes.map(code=>{const row=rowMap.get(code.code);const absent=row&&row.atClosure?row.absent:0;const remained=row&&row.atClosure?row.remained:0;const primary=absent>=remained?"Absent at reopening":"Still recorded at reopening";const count=absent>=remained?absent:remained;return <article key={code.code}><div className="outcome-code"><code>{code.code}</code><span className={code.critical?"critical":""}>{code.critical?"Critical":"Not critical"}</span></div><p>{code.description}</p><div className={`outcome-result ${row&&row.atClosure?"measured":"unavailable"}`}><strong>{row&&row.atClosure?primary:"Not measurable"}</strong><small>{row&&row.atClosure?`${count} of ${row.atClosure} available reopening ${row.atClosure===1?"record":"records"}`:"No reopening evidence"}</small></div></article>})}</div><section className={`recurrence-summary ${recurrence.reclosed?"measured":"unavailable"}`}><div><span>LATER-CLOSURE CHECK</span><h3>{recurrence.reclosed?`${recurrence.reclosed} later ${recurrence.reclosed===1?"closure":"closures"} available`:`Recurrence cannot be measured for this group`}</h3><p>{recurrence.reclosed?"The results below show whether each original code appeared in those later closure records.":"None of the observable exact-match restaurants had a later closure record, so the data cannot show whether these violations recurred."}</p></div>{recurrence.reclosed&&<ul>{selected.closure.codes.map(code=>{const returned=recurrenceMap.get(code.code)??0;return <li key={code.code}><code>{code.code}</code><strong>{returned} of {recurrence.reclosed}</strong><span>later closures</span></li>})}</ul>}</section></section>}
function ManagerSummary({selected,cohort,timeline,transitions,recurrence,mode,previous}:{selected:ClosureEpisode;cohort:ClosureEpisode[];timeline:ReturnType<typeof timelineAnalysis>;transitions:TransitionRow[];recurrence:ReturnType<typeof recurrenceAnalysis>;mode:ClosureMode;previous:ClosureEpisode|null}){const priority=[...transitions].filter(row=>row.atClosure>0).sort((a,b)=>(b.remained/b.atClosure)-(a.remained/a.atClosure))[0];const repeated=previous?selected.closure.codes.filter(code=>previous.closure.codes.some(item=>item.code===code.code)).length:0;return <section className="manager-summary" aria-label="Manager evidence summary"><div className="manager-summary-head"><span>{mode==="repeat"?"REPEAT-CLOSURE SUMMARY":"FIRST-CLOSURE SUMMARY"}</span><h3>{selected.name}</h3><p>{mode==="repeat"&&previous?`The available history includes an earlier closure on ${previous.closure.date}; ${repeated} current ${repeated===1?"code was":"codes were"} recorded then too.`:"No earlier closure was found for this CAMIS in the available snapshot. Use this path for orientation and prevention planning."}</p></div><div className="manager-summary-grid"><article><span>01 · CONFIRM THE RECORD</span><strong>{mode==="repeat"?"Compare both events":"Review Step 1"}</strong><p>{mode==="repeat"?"Bring the previous and current closure records into the next conversation with DOHMH or a qualified adviser.":"Use the official closure descriptions to prepare the questions you need answered by DOHMH or a qualified adviser."}</p><small>Your selected closure record remains the source.</small></article><article><span>02 · PREPARE THE BUSINESS</span><strong>Use the full range</strong><p>Plan cash, staffing, inventory, supplier, and customer decisions for more than one timing scenario.</p><small>Step 3 contains historical evidence; it is not a predicted date.</small></article><article><span>03 · VERIFY CLOSELY</span><strong>{mode==="repeat"&&repeated?`${repeated} repeated ${repeated===1?"code":"codes"}`:priority?.code??"No code ranked"}</strong><p>{mode==="repeat"&&repeated?"Start with the codes shared by the restaurant’s own closure records, then use Step 4 to compare the peer evidence.":priority?`Begin your evidence review with ${priority.description}, then return to Step 4 for its peer denominator and context.`:"The selected peer group did not provide enough matching evidence to rank your recorded items."}</p><small>{recurrence.reclosed?"Later-closure evidence is available in Step 4.":"No measurable later-closure signal was available."}</small></article></div><p className="manager-summary-source">Uses the closure context confirmed in Step 1 and the peer group selected in Step 2. Only DOHMH determines legal reopening status.</p></section>}

function ClosureContext({mode,priorEpisodes,onChange}:{mode:ClosureMode;priorEpisodes:ClosureEpisode[];onChange:(mode:ClosureMode)=>void}){const detected=priorEpisodes.length>0;return <section className="closure-context" aria-label="Confirm closure context"><div className="closure-context-copy"><span>CLOSURE HISTORY CHECK</span><h3>{detected?`${priorEpisodes.length} earlier recorded ${priorEpisodes.length===1?"closure":"closures"} found`:`No earlier recorded closure found`}</h3><p>{detected?`The newest earlier closure in this snapshot was ${priorEpisodes[0].closure.date}. Confirm how you want Six Days to review the selected event.`:"The public snapshot may be incomplete. Confirm whether this should be reviewed as a first closure or a repeat closure."}</p></div><div className="closure-mode-buttons" role="group" aria-label="Choose first or repeat closure path"><button type="button" className={mode==="first"?"active":""} aria-pressed={mode==="first"} onClick={()=>onChange("first")}><span>FIRST CLOSURE</span><strong>Help me understand what happens next</strong></button><button type="button" className={mode==="repeat"?"active":""} aria-pressed={mode==="repeat"} onClick={()=>onChange("repeat")}><span>REPEAT CLOSURE</span><strong>Show me what changed or returned</strong></button></div><small>“First” means no earlier closure was found in the available public history—not proof that no earlier closure occurred.</small></section>}

function RepeatClosureComparison({current,previous,priorCount}:{current:ClosureEpisode;previous:ClosureEpisode;priorCount:number}){const before=new Map(previous.closure.codes.map(code=>[code.code,code]));const now=new Map(current.closure.codes.map(code=>[code.code,code]));const repeated=[...now.values()].filter(code=>before.has(code.code));const added=[...now.values()].filter(code=>!before.has(code.code));const absent=[...before.values()].filter(code=>!now.has(code.code));return <section className="repeat-closure-comparison" aria-label="Current closure compared with previous recorded closure"><header><span>YOUR RESTAURANT · REPEAT-CLOSURE VIEW</span><h3>Current record compared with the previous closure</h3><p>{priorCount} earlier recorded {priorCount===1?"closure was":"closures were"} found. This comparison uses the most recent one: {previous.closure.date}.</p></header><div className="repeat-event-line"><article><span>PREVIOUS CLOSURE</span><strong>{previous.closure.date}</strong><p>{previous.closure.codes.length} recorded codes · score {previous.closure.score??"not recorded"}</p></article><i aria-hidden="true">→</i><article><span>CURRENT CLOSURE</span><strong>{current.closure.date}</strong><p>{current.closure.codes.length} recorded codes · score {current.closure.score??"not recorded"}</p></article></div><div className="repeat-code-groups"><article className="returned"><span>RECORDED IN BOTH</span><strong>{repeated.length}</strong><p>{repeated.length?repeated.map(code=>code.code).join(", "):"No shared codes"}</p></article><article><span>NEW ON CURRENT RECORD</span><strong>{added.length}</strong><p>{added.length?added.map(code=>code.code).join(", "):"No new codes"}</p></article><article><span>NOT ON CURRENT RECORD</span><strong>{absent.length}</strong><p>{absent.length?absent.map(code=>code.code).join(", "):"No earlier codes absent"}</p></article></div><footer>Shared codes show a public-record pattern. They do not prove that the same condition persisted or that the same corrective action is required.</footer></section>}
function OutcomeFlow({total,reopened,eligible,reclosed}:{total:number;reopened:number;eligible:number;reclosed:number}){const stages=[{value:total,label:"Retained episodes",detail:"Sharing selected criteria"},{value:reopened,label:"Reopening matched",detail:percent(reopened,total)},{value:eligible,label:"Observable follow-up",detail:"At least 365 days"},{value:reclosed,label:"Later closure recorded",detail:percent(reclosed,eligible)}];return <div className="outcome-flow" aria-label="Recorded outcomes for the retained peer set">{stages.map((stage,i)=><div className="outcome-stage" key={stage.label}><article><span>0{i+1}</span><strong>{stage.value}</strong><h3>{stage.label}</h3><p>{stage.detail}</p></article>{i<stages.length-1&&<i aria-hidden="true">→</i>}</div>)}</div>}
function RecurringCodes({recurrence,cohort}:{recurrence:ReturnType<typeof recurrenceAnalysis>;cohort:ClosureEpisode[]}){const allReturned=recurrence.codes.length>1&&recurrence.codes.every(row=>row.rate===100);return <div className="embedded-repeat"><div className="repeat-codes-heading"><span>ORIGINAL CODES RECORDED AGAIN AT A LATER CLOSURE</span><h3>{recurrence.codes.length?allReturned?`All ${recurrence.codes.length} recurring codes appeared in every qualifying later-closure episode`:`${recurrence.codes.length} recurring ${recurrence.codes.length===1?"code":"codes"} found`:"No recurring original codes found"}</h3></div>{recurrence.codes.length?(allReturned?<div className="all-returned"><div><strong>100%</strong><p>Each code below appeared in every qualifying later-closure episode.</p></div><ul>{recurrence.codes.slice(0,8).map(row=><li key={row.code}><code>{row.code}</code><span>{descriptionFor(cohort,row.code)}</span></li>)}</ul></div>:<div className="repeat-grid">{recurrence.codes.slice(0,6).map((row,i)=><article key={row.code}><span>0{i+1}</span><code>{row.code}</code><h3>{descriptionFor(cohort,row.code)}</h3><strong>{row.rate.toFixed(0)}%</strong><p>Recorded again in {row.count} of {recurrence.reclosed} later-closure episodes</p></article>)}</div>):<div className="repeat-empty"><strong>{recurrence.reclosed?"The later closures involved different recorded codes.":"No later closure was matched."}</strong><p>{recurrence.reclosed?`The ${recurrence.reclosed} later-closure episodes did not repeat an original code.`:"No eligible episode in this peer set had a later recorded closure within 365 observable days."}</p></div>}<p className="plain-note">This analysis now includes both “closed” and “re-closed” DOHMH actions. It remains observational and does not predict another closure or identify a corrective action.</p></div>}
function ClosureCard({episode}:{episode:ClosureEpisode}){return <div className="record-card"><div className="record-top"><div><span>OFFICIAL RECORDED CLOSURE</span><h3>{episode.name}</h3><p>{episode.borough} · CAMIS {episode.camis}</p></div><strong className={episode.reopening?"status-open":"status-closed"}>{episode.reopening?"REOPENING RECORDED":"NO REOPENING MATCHED"}</strong></div><div className="record-facts"><article><span>Closure</span><strong>{episode.closure.date}</strong></article><article><span>Score</span><strong>{episode.closure.score??"—"}</strong></article><article><span>Recorded reopening</span><strong>{episode.reopening?.date??"Not matched"}</strong></article></div><h4>Violations recorded at closure</h4><div className="code-list">{episode.closure.codes.map(c=><article key={c.code}><code>{c.code}</code><div><span className={c.critical?"critical-tag":"noncritical-tag"}>{c.critical?"Critical":"Not critical"}</span><p>{c.description}</p></div></article>)}</div><p className="record-boundary">Critical status is reproduced from the NYC Open Data critical_flag field. This does not determine required corrections or authorize reopening.</p></div>}
function PeerSetMap({paths,episodes}:{paths:BoroughMapPath[];episodes:ClosureEpisode[]}){const [focused,setFocused]=useState("All NYC");const boroughs=["Bronx","Brooklyn","Manhattan","Queens","Staten Island"];const count=(borough:string)=>episodes.filter(e=>e.borough===borough).length;const activeCount=focused==="All NYC"?episodes.length:count(focused);const max=Math.max(1,...boroughs.map(count));return <figure className="peer-set-map"><div><span>GEOGRAPHIC DISTRIBUTION</span><strong>{focused}</strong><p>{activeCount} of {episodes.length} episodes · {percent(activeCount,episodes.length)}</p><ul>{boroughs.map(borough=><li key={borough}><button type="button" className={focused===borough?"active":""} onMouseEnter={()=>setFocused(borough)} onFocus={()=>setFocused(borough)} onClick={()=>setFocused(borough)}><span><strong>{count(borough)}</strong><small>{borough}</small></span><i style={{width:`${count(borough)/max*100}%`}}/></button></li>)}</ul></div><svg viewBox="0 0 720 430" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Borough distribution for ${episodes.length} proposed peer closure episodes`}>{paths.map(path=>{const boroughCount=count(path.name);const intensity=boroughCount/max;return <path key={path.name} d={path.path} fill={`rgba(177,131,36,${.18+intensity*.82})`} fillRule="evenodd" role="button" tabIndex={0} aria-label={`${path.name}: ${boroughCount} episodes`} className={focused===path.name?"active":""} onMouseEnter={()=>setFocused(path.name)} onFocus={()=>setFocused(path.name)} onClick={()=>setFocused(path.name)}/>})}</svg><figcaption>Choose or point to a borough to see its share. Geography is descriptive and does not explain outcomes.</figcaption></figure>}
function JourneyMap({paths,episodes,allMatches,selected,activeArea,onSelectArea}:{paths:BoroughMapPath[];episodes:ClosureEpisode[];allMatches:ClosureEpisode[];selected:ClosureEpisode;activeArea:string;onSelectArea:(area:string)=>void}){
  const [focused,setFocused]=useState<ClosureEpisode|null>(null);
  const areas=["All NYC","Bronx","Brooklyn","Manhattan","Queens","Staten Island"];
  const counts=new Map<string,number>();
  allMatches.forEach(e=>counts.set(e.borough,(counts.get(e.borough)??0)+1));
  const projection=paths[0]?.projection;
  const point=(longitude:number,latitude:number)=>projection?{x:projection.offsetX+(longitude-projection.minLon)*projection.scale,y:projection.offsetY+(projection.maxLat-latitude)*projection.scale}:{x:0,y:0};
  const selectedPoint=selected.latitude!==null&&selected.longitude!==null?point(selected.longitude,selected.latitude):null;
  return <figure className="journey-map"><div className="map-heading"><div><span>INTERACTIVE AREA MAP</span><figcaption>Choose where to compare this closure</figcaption><p>Select an area, then point to any gold marker to inspect that restaurant’s recorded outcome.</p></div><strong>{activeArea}</strong></div><div className="map-layout"><div className="map-area-buttons" aria-label="Choose comparison area">{areas.map(area=><button type="button" key={area} className={activeArea===area?"active":""} onClick={()=>{setFocused(null);onSelectArea(area)}}><span>{area}</span><b>{area==="All NYC"?allMatches.length:counts.get(area)??0}</b></button>)}</div><div className="map-stage"><svg viewBox="0 0 720 430" preserveAspectRatio="xMidYMid meet" role="img" aria-label={`Map of ${activeArea} showing ${episodes.length} comparable closure records`}>{paths.map(p=><path key={p.name} d={p.path} fill="#d8cdb8" fillRule="evenodd"/>)}{episodes.filter(e=>e.latitude!==null&&e.longitude!==null).map(e=>{const p=point(e.longitude!,e.latitude!);return <circle key={e.id} cx={p.x} cy={p.y} r={focused?.id===e.id?8:5} role="button" tabIndex={0} aria-label={`${e.name}, closed ${e.closure.date}${e.reopening?`, reopened after ${e.reopeningDays} days`:`, no reopening record matched`}`} onMouseEnter={()=>setFocused(e)} onFocus={()=>setFocused(e)} onClick={()=>setFocused(e)}/>})}{selectedPoint&&<rect x={selectedPoint.x-8} y={selectedPoint.y-8} width="16" height="16"/>}</svg><div className="map-inspector" aria-live="polite">{focused?<><span>COMPARABLE RESTAURANT</span><strong>{focused.name}</strong><p>{focused.borough} · closed {focused.closure.date}</p><b>{focused.reopening?`${focused.reopeningDays} recorded days to reopening`:"No reopening record matched"}</b></>:<><span>EXPLORE THE DATA</span><strong>{episodes.length} comparable closures</strong><p>Hover, focus, or tap a gold marker for its recorded outcome.</p></>}</div></div></div><p className="map-legend"><i/> Comparable closure <b/> Selected restaurant <span>{episodes.filter(e=>e.latitude===null||e.longitude===null).length} records lack coordinates</span></p></figure>}

type TransitionRow={code:string;description:string;atClosure:number;absent:number;remained:number;appeared:number};
function transitionRows(episodes:ClosureEpisode[]){const eligible=episodes.filter(e=>e.reopening);const rows=new Map<string,TransitionRow>();eligible.forEach(e=>{const before=new Map(e.closure.codes.map(c=>[c.code,c]));const after=new Map(e.reopening!.codes.map(c=>[c.code,c]));before.forEach((c,code)=>{const r=rows.get(code)??{code,description:c.description,atClosure:0,absent:0,remained:0,appeared:0};r.atClosure++;if(after.has(code))r.remained++;else r.absent++;rows.set(code,r)});after.forEach((c,code)=>{if(before.has(code))return;const r=rows.get(code)??{code,description:c.description,atClosure:0,absent:0,remained:0,appeared:0};r.appeared++;rows.set(code,r)})});const list=[...rows.values()];return {eligible:eligible.length,rows:list,topRemained:[...list].sort((a,b)=>b.remained-a.remained)[0],topAppeared:[...list].sort((a,b)=>b.appeared-a.appeared)[0]}}
function TransitionList({title,rows,value}:{title:string;rows:TransitionRow[];value:(row:TransitionRow)=>string}){return <section><h3>{title}</h3>{rows.length?rows.map(r=><article key={r.code}><div><code>{r.code}</code><span>{r.description}</span></div><strong>{value(r)}</strong></article>):<p>No qualifying codes.</p>}</section>}
function TimelineBars({values}:{values:number[]}){const buckets=[["0–3",0,3],["4–7",4,7],["8–14",8,14],["15–30",15,30],["31+",31,Infinity]] as const;const counts=buckets.map(([,min,max])=>values.filter(v=>v>=min&&v<=max).length);return <div className="timeline-bars" aria-label="Share of matched reopening records by elapsed days">{buckets.map(([label],i)=><article key={label}><strong>{counts[i]}</strong><i style={{width:`${values.length?counts[i]/values.length*100:0}%`}}/><span>{label} days · {percent(counts[i],values.length)}</span></article>)}</div>}
function FetchStateLabel({state,fetchedAt}:{state:FetchState;fetchedAt:string}){return <p className={`live-record-state ${state}`}>{state==="loading"?"Checking NYC Open Data…":state==="success"?`Latest available rows retrieved ${fmt.format(new Date())}.`:state==="fallback"?`Live request failed—showing the latest saved closure or reopening action from the ${fmt.format(new Date(fetchedAt))} snapshot, not necessarily the latest inspection.`:"Waiting for a restaurant selection."}</p>}
function LatestRecord({closure,latest}:{closure:InspectionEvent;latest:InspectionEvent[]}){if(!latest.length)return <p className="journey-empty">No official row is available for comparison.</p>;const before=new Set(closure.codes.map(c=>c.code));const after=new Set(latest.flatMap(event=>event.codes.map(c=>c.code)));return <div className="latest-record"><div className="latest-closure"><span>SELECTED CLOSURE</span><strong>{closure.date}</strong><p>{closure.action}</p></div><div className="latest-events"><span>NEWEST INSPECTION DATE · {latest[0].date}</span>{latest.map(event=><article key={event.id}><strong>{event.action}</strong><p>Score {event.score??"—"} · grade {event.grade??"not recorded"} · {event.codes.length} recorded codes</p><small>Dataset record date {event.recordDate??"not recorded"}</small></article>)}</div><div className="latest-code-change"><article><strong>{[...before].filter(c=>!after.has(c)).length}</strong><span>closure codes not recorded on newest date</span></article><article><strong>{[...before].filter(c=>after.has(c)).length}</strong><span>closure codes also recorded</span></article><article><strong>{[...after].filter(c=>!before.has(c)).length}</strong><span>other recorded codes</span></article></div></div>}
function descriptionFor(episodes:ClosureEpisode[],code:string){for(const e of episodes){const c=[...e.closure.codes,...(e.reopening?.codes??[]),...(e.laterClosure?.codes??[])].find(x=>x.code===code);if(c)return c.description}return "Recorded violation"}
function percent(n:number,d:number){return d?`${(n/d*100).toFixed(1)}%`:"—"}
