"use client";

import { useEffect, useMemo, useState } from "react";
import { groupInspectionRows, matchCohort, recurrenceAnalysis, timelineAnalysis, type ClosureEpisode, type CohortFilters, type InspectionEvent, type RawInspectionRow } from "../lib/closure-analysis";
import type { BoroughMapPath } from "../lib/inspections";
import { BookChapters } from "./BookChapters";

const fmt=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"});
type FetchState="idle"|"loading"|"success"|"fallback";

export function ConnectedJourney({episodes,events,boroughMap,fetchedAt}:{episodes:ClosureEpisode[];events:InspectionEvent[];boroughMap:BoroughMapPath[];fetchedAt:string}){
  const sample=useMemo(()=>episodes.find(e=>e.reopening&&e.closure.codes.length>=3&&matchCohort(e,episodes,{scope:"borough",burdenTolerance:2,periodYears:2,inspectionType:true,minSharedCodes:1}).length>=10)??episodes.find(e=>e.reopening&&e.closure.codes.length>=3)??episodes[0],[episodes]);
  const [selected,setSelected]=useState<ClosureEpisode|null>(null);
  const [query,setQuery]=useState("");
  const [filters,setFilters]=useState<CohortFilters>({scope:"borough",burdenTolerance:99,periodYears:2,inspectionType:true,minSharedCodes:1});
  const [selectedCodes,setSelectedCodes]=useState<string[]>([]);
  const [latest,setLatest]=useState<InspectionEvent[]>([]);
  const [fetchState,setFetchState]=useState<FetchState>("idle");
  const matches=useMemo(()=>{const q=query.trim().toLowerCase();return q.length<2?[]:episodes.filter(e=>`${e.name} ${e.camis} ${e.borough} ${e.zipcode}`.toLowerCase().includes(q)).slice(0,7)},[episodes,query]);
  const activeCode=selectedCodes[0]??selected?.closure.codes.find(c=>c.critical)?.code??selected?.closure.codes[0]?.code??"";
  const cohort=useMemo(()=>{if(!selected||!activeCode)return[];const matched=matchCohort(selected,episodes,{...filters,minSharedCodes:0});return matched.filter(e=>e.closure.codes.some(c=>c.code===activeCode))},[selected,episodes,filters,activeCode]);
  const transitions=useMemo(()=>transitionRows(cohort),[cohort]);
  const recurrence=useMemo(()=>recurrenceAnalysis(cohort,fetchedAt.slice(0,10)),[cohort,fetchedAt]);
  const timeline=useMemo(()=>timelineAnalysis(cohort,fetchedAt.slice(0,10)),[cohort,fetchedAt]);
  const latestRecords=useMemo(()=>{const source=fetchState==="success"?latest:events;return selected?source.filter(e=>e.camis===selected.camis).sort((a,b)=>b.date.localeCompare(a.date)):[]},[events,fetchState,latest,selected]);

  useEffect(()=>{if(!selected)return;let cancelled=false;const params=new URLSearchParams({"$select":"camis,dba,boro,building,street,zipcode,inspection_date,inspection_type,action,violation_code,violation_description,critical_flag,score,grade,grade_date,record_date,latitude,longitude","$where":`camis='${selected.camis}'`,"$order":"inspection_date DESC","$limit":"50000"});fetch(`https://data.cityofnewyork.us/resource/43nn-pn8j.json?${params}`).then(r=>{if(!r.ok)throw new Error("request failed");return r.json()}).then((rows:RawInspectionRow[])=>{if(!cancelled){setLatest(groupInspectionRows(rows));setFetchState("success")}}).catch(()=>{if(!cancelled)setFetchState("fallback")});return()=>{cancelled=true}},[selected]);
  useEffect(()=>{if(!sample)return;const load=()=>{setSelected(sample);setQuery(sample.name);setSelectedCodes([sample.closure.codes.find(c=>c.critical)?.code??sample.closure.codes[0]?.code??""]);setLatest([]);setFetchState("loading")};window.addEventListener("six-days-load-sample",load);return()=>window.removeEventListener("six-days-load-sample",load)},[sample]);
  const choose=(episode:ClosureEpisode)=>{setSelected(episode);setQuery(episode.name);setSelectedCodes([episode.closure.codes.find(c=>c.critical)?.code??episode.closure.codes[0]?.code??""]);setFilters(f=>({...f,scope:"borough",boroughOverride:episode.borough}));setLatest([]);setFetchState("loading")};

  return <BookChapters>
    <section className="book-chapter owner-step" id="find"><Step n="01" title="Find my restaurant" question="Why was my restaurant closed?"/><p className="step-intro">Begin with the official public record. Search recent NYC closure events to see what was recorded—not an interpretation of what happened.</p><Impact>Shows which documented violations are demanding the owner’s immediate attention and resources.</Impact><div className="finder"><label htmlFor="restaurant-search">Restaurant name or CAMIS number</label><div className="search-row"><input id="restaurant-search" value={query} onChange={e=>{setQuery(e.target.value);setSelected(null)}} placeholder="Start typing a restaurant name…"/><span>NYC OPEN DATA</span></div>{matches.length>0&&!selected&&<ul className="search-results">{matches.map(e=><li key={e.id}><button onClick={()=>choose(e)}><strong>{e.name}</strong><span>{e.borough} · closed {e.closure.date} · CAMIS {e.camis}</span></button></li>)}</ul>}{selected&&<ClosureCard episode={selected}/>}</div></section>

    <section className="book-chapter owner-step context-step" id="compare">
      <Step n="02" title="Compare and see outcomes" question="What happened to similarly closed restaurants?"/>
      <p className="step-intro">Choose an area and one violation from your closure record. The results show who reopened, how long it took, and how many later closed again.</p>
      <Impact>Turns one selected comparison group into clear historical outcomes for the owner.</Impact>
      {selected?<>
        <p className="selected-context"><strong>{selected.name}</strong><span>{selected.borough}</span><span>{selected.closure.codes.length} recorded violations</span></p>
        <div className="comparison-builder"><label><span>Search area · currently {filters.scope==="city"?"all NYC":filters.boroughOverride||selected.borough}</span><select value={filters.scope==="city"?"city":filters.boroughOverride||selected.borough} onChange={e=>setFilters({...filters,scope:e.target.value==="city"?"city":"borough",boroughOverride:e.target.value==="city"?undefined:e.target.value})}><option value="city">All NYC</option>{["Bronx","Brooklyn","Manhattan","Queens","Staten Island"].map(b=><option key={b} value={b}>{b}</option>)}</select></label><label><span>Select violation · {selected.closure.codes.length} available</span><select value={activeCode} onChange={e=>setSelectedCodes([e.target.value])}>{selected.closure.codes.map(c=><option key={c.code} value={c.code}>{c.code} · {c.description}</option>)}</select></label></div>
        <OutcomeFlow total={cohort.length} reopened={cohort.filter(e=>e.reopening).length} eligible={recurrence.eligible} reclosed={recurrence.reclosed}/>
        <JourneyMap paths={boroughMap} episodes={cohort} selected={selected}/>
        <p className="cohort-rule"><strong>One retained comparison group:</strong> restaurants with violation {activeCode} · same inspection type · two-year window · {filters.scope==="city"?"all NYC":filters.boroughOverride||selected.borough}. Every result below and in Steps 3–5 uses these same {cohort.length} closure cases.</p>
        <RecurringCodes recurrence={recurrence} cohort={cohort}/>
      </>:<EmptyState/>}
    </section>

    <section className="book-chapter owner-step" id="change">
      <Step n="04" title="Study the reopening record" question="What changed before similar restaurants reopened?"/>
      <p className="step-intro">For each restaurant retained from Step 2, we compare its closure record with its next recorded reopening event.</p>
      <Impact>Shows which documented issues changed or remained before comparable restaurants reopened.</Impact>
      {selected?<>
        <p className="cohort-context"><strong>Across {transitions.eligible} comparable restaurants</strong><span>we counted how recorded violation-code occurrences changed from closure to the next reopening record.</span></p>
        <div className="change-summary"><article><strong>{transitions.rows.reduce((sum,row)=>sum+row.absent,0)}</strong><span>code occurrences absent at reopening</span></article><article><strong>{transitions.rows.reduce((sum,row)=>sum+row.remained,0)}</strong><span>code occurrences still present</span></article><article><strong>{transitions.rows.reduce((sum,row)=>sum+row.appeared,0)}</strong><span>new code occurrences at reopening</span></article></div>
        <p className="transition-summary-copy">The lists below describe different restaurants. A code can remain for one restaurant but appear as new for another, so the same code may appear in more than one list.</p>
        <div className="change-grid"><TransitionList title="Absent at reopening" rows={transitions.rows.filter(r=>r.absent>0).sort((a,b)=>b.absent-a.absent).slice(0,6)} value={r=>`${r.absent} of ${r.atClosure} · ${percent(r.absent,r.atClosure)}`}/><TransitionList title="Still present at reopening" rows={transitions.rows.filter(r=>r.remained>0).sort((a,b)=>b.remained-a.remained).slice(0,6)} value={r=>`${r.remained} of ${r.atClosure} · ${percent(r.remained,r.atClosure)}`}/><TransitionList title="Not at closure; new at reopening" rows={transitions.rows.filter(r=>r.appeared>0).sort((a,b)=>b.appeared-a.appeared).slice(0,6)} value={r=>`${r.appeared} of ${transitions.eligible} · ${percent(r.appeared,transitions.eligible)}`}/></div>
        <p className="plain-note">“No longer recorded” means absent from the next public reopening record; it does not identify the correction performed or prove causation.</p>
      </>:<EmptyState/>}
    </section>

    <section className="book-chapter owner-step timeline-step" id="timeline"><Step n="05" title="Understand the timeline" question="How long did comparable cases take?"/><Impact>Helps the owner prepare cash flow, staffing, inventory, and suppliers for a realistic closure duration.</Impact>{selected?<><div className="timeline-lead"><strong>{timeline.median??"—"}</strong><div><h3>median recorded days</h3><p>among {timeline.matched} matched reopening records from the same {cohort.length}-case comparison group.</p></div></div><TimelineBars values={timeline.values}/><div className="delay-grid">{timeline.thresholds.map(t=><article key={t.days}><strong>{t.rate.toFixed(1)}%</strong><p>{t.without} of {t.eligible} eligible cases had no reopening recorded by day {t.days}</p></article>)}</div><p className="plain-note">Each threshold shows its own eligible denominator because recent closures may not yet have enough observable time. This is a historical benchmark, not a forecast.</p></>:<EmptyState/>}</section>

    <section className="book-chapter owner-step monitor-step" id="monitor"><Step n="06" title="Check the latest record" question="What has NYC recorded next?"/><p className="step-intro">The app requests the newest available NYC Open Data rows for the selected restaurant.</p><Impact>Shows what official information has changed and what the owner should verify next with DOHMH.</Impact>{selected?<><FetchStateLabel state={fetchState} fetchedAt={fetchedAt}/><LatestRecord closure={selected.closure} latest={latestRecords[0]}/><div className="final-boundary"><strong>Six Days informs. The owner decides.</strong><p>This is the latest available public record, not continuous monitoring or confirmation of operating status. Only NYC DOHMH authorizes reopening.</p></div></>:<EmptyState/>}</section>
  </BookChapters>
}

function Step({n,title,question}:{n:string;title:string;question:string}){const display={"04":"03","05":"04","06":"05"}[n]??n;return <><div className="step-label"><span>STEP {display}</span><i>{title}</i></div><h2>{question}</h2></>}
function Impact({children}:{children:React.ReactNode}){return <p className="business-impact"><strong>Business impact</strong>{children}</p>}
function EmptyState(){return <p className="journey-empty">Choose a restaurant in Step 1 to calculate this section.</p>}
function OutcomeFlow({total,reopened,eligible,reclosed}:{total:number;reopened:number;eligible:number;reclosed:number}){const stages=[{value:total,label:"Comparable closures",detail:"Selected in this step"},{value:reopened,label:"Reopening recorded",detail:percent(reopened,total)},{value:eligible,label:"Eligible for follow-up",detail:"365 observable days"},{value:reclosed,label:"Closed again",detail:percent(reclosed,eligible)}];return <div className="outcome-flow" aria-label="Outcome flow for the selected comparison group">{stages.map((stage,i)=><div className="outcome-stage" key={stage.label}><article><span>0{i+1}</span><strong>{stage.value}</strong><h3>{stage.label}</h3><p>{stage.detail}</p></article>{i<stages.length-1&&<i aria-hidden="true">→</i>}</div>)}</div>}
function RecurringCodes({recurrence,cohort}:{recurrence:ReturnType<typeof recurrenceAnalysis>;cohort:ClosureEpisode[]}){const allReturned=recurrence.codes.length>1&&recurrence.codes.every(row=>row.rate===100);return <div className="embedded-repeat"><div className="repeat-codes-heading"><span>ORIGINAL VIOLATIONS RECORDED AGAIN</span><h3>{recurrence.codes.length?allReturned?`All ${recurrence.codes.length} recurring codes returned`:`${recurrence.codes.length} recurring ${recurrence.codes.length===1?"code":"codes"} found`:"No recurring original codes found"}</h3></div>{recurrence.codes.length?(allReturned?<div className="all-returned"><div><strong>100%</strong><p>Each code below appeared in every qualifying repeat-closure record.</p></div><ul>{recurrence.codes.slice(0,8).map(row=><li key={row.code}><code>{row.code}</code><span>{descriptionFor(cohort,row.code)}</span></li>)}</ul></div>:<div className="repeat-grid">{recurrence.codes.slice(0,6).map((row,i)=><article key={row.code}><span>0{i+1}</span><code>{row.code}</code><h3>{descriptionFor(cohort,row.code)}</h3><strong>{row.rate.toFixed(0)}%</strong><p>Recorded again in {row.count} of {recurrence.reclosed} repeat-closure cases</p></article>)}</div>):<div className="repeat-empty"><strong>{recurrence.reclosed?"The repeat closure involved different violations.":"No later closure was recorded."}</strong><p>{recurrence.reclosed?`The ${recurrence.reclosed} restaurant that closed again did not repeat an original violation code.`:"No eligible restaurant in this comparison group had a later recorded closure within 365 days."}</p></div>}<p className="plain-note">These results come only from the group selected above. They describe historical records and do not predict another closure.</p></div>}
function ClosureCard({episode}:{episode:ClosureEpisode}){return <div className="record-card"><div className="record-top"><div><span>OFFICIAL RECORDED CLOSURE</span><h3>{episode.name}</h3><p>{episode.borough} · CAMIS {episode.camis}</p></div><strong className={episode.reopening?"status-open":"status-closed"}>{episode.reopening?"REOPENING RECORDED":"NO REOPENING MATCHED"}</strong></div><div className="record-facts"><article><span>Closure</span><strong>{episode.closure.date}</strong></article><article><span>Score</span><strong>{episode.closure.score??"—"}</strong></article><article><span>Recorded reopening</span><strong>{episode.reopening?.date??"Not matched"}</strong></article></div><h4>Violations recorded at closure</h4><div className="code-list">{episode.closure.codes.map(c=><article key={c.code}><code>{c.code}</code><div><span className={c.critical?"critical-tag":"noncritical-tag"}>{c.critical?"Critical":"Not critical"}</span><p>{c.description}</p></div></article>)}</div><p className="record-boundary">Critical status is reproduced from the NYC Open Data critical_flag field. This does not determine required corrections or authorize reopening.</p></div>}
function JourneyMap({paths,episodes,selected}:{paths:BoroughMapPath[];episodes:ClosureEpisode[];selected:ClosureEpisode}){return <figure className="journey-map"><figcaption>Where the {episodes.length} comparable closure records are located</figcaption><svg viewBox="0 0 720 430" role="img" aria-label="NYC map showing comparable closure records">{paths.map(p=><path key={p.name} d={p.path} fill="#d8cdb8" fillRule="evenodd"/>)}{episodes.filter(e=>e.latitude!==null&&e.longitude!==null).map(e=><circle key={e.id} cx={(e.longitude!+74.26)/.56*720} cy={(40.92-e.latitude!)/.43*430} r="3"/>)}{selected.latitude!==null&&selected.longitude!==null&&<rect x={(selected.longitude+74.26)/.56*720-7} y={(40.92-selected.latitude)/.43*430-7} width="14" height="14"/>}</svg><p>Gold circles: comparable cases · red square: selected restaurant · missing coordinates: {episodes.filter(e=>e.latitude===null||e.longitude===null).length}</p></figure>}

type TransitionRow={code:string;description:string;atClosure:number;absent:number;remained:number;appeared:number};
function transitionRows(episodes:ClosureEpisode[]){const eligible=episodes.filter(e=>e.reopening);const rows=new Map<string,TransitionRow>();eligible.forEach(e=>{const before=new Map(e.closure.codes.map(c=>[c.code,c]));const after=new Map(e.reopening!.codes.map(c=>[c.code,c]));before.forEach((c,code)=>{const r=rows.get(code)??{code,description:c.description,atClosure:0,absent:0,remained:0,appeared:0};r.atClosure++;if(after.has(code))r.remained++;else r.absent++;rows.set(code,r)});after.forEach((c,code)=>{if(before.has(code))return;const r=rows.get(code)??{code,description:c.description,atClosure:0,absent:0,remained:0,appeared:0};r.appeared++;rows.set(code,r)})});const list=[...rows.values()];return {eligible:eligible.length,rows:list,topRemained:[...list].sort((a,b)=>b.remained-a.remained)[0],topAppeared:[...list].sort((a,b)=>b.appeared-a.appeared)[0]}}
function TransitionList({title,rows,value}:{title:string;rows:TransitionRow[];value:(row:TransitionRow)=>string}){return <section><h3>{title}</h3>{rows.length?rows.map(r=><article key={r.code}><div><code>{r.code}</code><span>{r.description}</span></div><strong>{value(r)}</strong></article>):<p>No qualifying codes.</p>}</section>}
function TimelineBars({values}:{values:number[]}){const buckets=[["0–3",0,3],["4–7",4,7],["8–14",8,14],["15–30",15,30],["31+",31,Infinity]] as const;const counts=buckets.map(([,min,max])=>values.filter(v=>v>=min&&v<=max).length);const max=Math.max(1,...counts);return <div className="timeline-bars">{buckets.map(([label],i)=><article key={label}><strong>{counts[i]}</strong><i style={{width:`${counts[i]/max*100}%`}}/><span>{label} days · {percent(counts[i],values.length)}</span></article>)}</div>}
function FetchStateLabel({state,fetchedAt}:{state:FetchState;fetchedAt:string}){return <p className={`live-record-state ${state}`}>{state==="loading"?"Checking NYC Open Data…":state==="success"?`Latest available rows retrieved ${fmt.format(new Date())}.`:state==="fallback"?`Live request failed—showing the saved snapshot from ${fmt.format(new Date(fetchedAt))}.`:"Waiting for a restaurant selection."}</p>}
function LatestRecord({closure,latest}:{closure:InspectionEvent;latest?:InspectionEvent}){if(!latest)return <p className="journey-empty">No official row is available for comparison.</p>;const before=new Set(closure.codes.map(c=>c.code));const after=new Set(latest.codes.map(c=>c.code));return <div className="latest-record"><div className="latest-columns"><section><span>SELECTED CLOSURE</span><strong>{closure.date}</strong><p>{closure.action}</p><small>Score {closure.score??"—"} · grade {closure.grade??"not recorded"}</small></section><i>→</i><section><span>LATEST AVAILABLE RECORD</span><strong>{latest.date}</strong><p>{latest.action}</p><small>Score {latest.score??"—"} · grade {latest.grade??"not recorded"}</small></section></div><div className="latest-code-change"><article><strong>{[...before].filter(c=>!after.has(c)).length}</strong><span>codes no longer recorded</span></article><article><strong>{[...before].filter(c=>after.has(c)).length}</strong><span>codes still recorded</span></article><article><strong>{[...after].filter(c=>!before.has(c)).length}</strong><span>newly recorded codes</span></article></div></div>}
function descriptionFor(episodes:ClosureEpisode[],code:string){for(const e of episodes){const c=[...e.closure.codes,...(e.reopening?.codes??[]),...(e.laterClosure?.codes??[])].find(x=>x.code===code);if(c)return c.description}return "Recorded violation"}
function percent(n:number,d:number){return d?`${(n/d*100).toFixed(1)}%`:"—"}
