"use client";

import { useMemo, useState } from "react";

type Restaurant={camis:string;name:string;borough:string;zipcode:string;closureDate:string;action:string;score:number|null;criticalCount:number;inspectionType:string;reopeningDate:string|null;reopeningDays:number|null;codes:Array<{code:string;description:string}>;reopeningCodes:Array<{code:string;description:string}>;laterClosureCodes:string[];laterClosureCount:number};
type Benchmark={borough:string;zipcode:string;closureDate:string;reopeningDays:number|null;codes:string[];criticalCount:number;inspectionType:string;reopeningCodes:string[];laterClosureCodes:string[]};
type Repeat={code:string;description:string;repeatedCount:number;repeatRate:number};

function median(values:number[]){const a=[...values].sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function pct(n:number,d:number){return d?`${(n/d*100).toFixed(0)}%`:"—"}

export function OwnerWizard({restaurants,benchmarks,repeats,fetchedAt}:{restaurants:Restaurant[];benchmarks:Benchmark[];repeats:Repeat[];fetchedAt:string}){
  const sample=restaurants.find(r=>r.reopeningDays!==null&&r.codes.length>=3)??restaurants[0];
  const [restaurant,setRestaurant]=useState<Restaurant|null>(null);
  const [step,setStep]=useState(0);
  const [query,setQuery]=useState("");
  const [scope,setScope]=useState<"zip"|"borough"|"city">("borough");
  const matches=useMemo(()=>query.trim().length<2?[]:restaurants.filter(r=>`${r.name} ${r.camis}`.toLowerCase().includes(query.toLowerCase())).slice(0,5),[query,restaurants]);
  const comparable=useMemo(()=>restaurant?benchmarks.filter(b=>{
    const geography=scope==="city"||b.borough===restaurant.borough&&(scope==="borough"||b.zipcode===restaurant.zipcode);
    const sharedViolation=b.codes.some(code=>restaurant.codes.some(v=>v.code===code));
    const similarBurden=Math.abs(b.codes.length-restaurant.codes.length)<=2;
    const sameInspection=b.inspectionType===restaurant.inspectionType;
    const withinPeriod=Math.abs(new Date(b.closureDate).getTime()-new Date(restaurant.closureDate).getTime())<=730*86400000;
    return geography&&sharedViolation&&similarBurden&&sameInspection&&withinPeriod;
  }):[],[restaurant,benchmarks,scope]);
  const matchedDays=comparable.flatMap(b=>b.reopeningDays===null?[]:[b.reopeningDays]);
  const med=median(matchedDays);
  const repeatMatches=restaurant?repeats.filter(r=>restaurant.codes.some(v=>v.code===r.code)).slice(0,4):[];
  const disappeared=restaurant?.codes.filter(v=>!restaurant.reopeningCodes.some(r=>r.code===v.code))??[];
  const remained=restaurant?.codes.filter(v=>restaurant.reopeningCodes.some(r=>r.code===v.code))??[];
  const appeared=restaurant?.reopeningCodes.filter(v=>!restaurant.codes.some(r=>r.code===v.code))??[];
  const cohortRecurrence=useMemo(()=>{const counts=new Map<string,number>();comparable.forEach(b=>b.laterClosureCodes.forEach(code=>{if(b.codes.includes(code))counts.set(code,(counts.get(code)||0)+1)}));return [...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4)},[comparable]);
  const steps=["My closure","Similar cases","Reopening change","Repeat closures","Timeline","Live record"];
  const choose=(r:Restaurant)=>{setRestaurant(r);setQuery(r.name);setStep(1)};
  const restart=()=>{setRestaurant(null);setQuery("");setStep(0)};

  return <main className="wizard-page">
    <header className="wizard-header"><button className="wizard-brand" onClick={restart}>Six Days</button><div className="wizard-progress">{steps.map((label,index)=><button key={label} className={index===step?"active":index<step?"done":""} disabled={!restaurant&&index>0} onClick={()=>restaurant&&setStep(index)}><b>{index+1}</b><span>{label}</span></button>)}</div><span className="live-dot"><i/> NYC OPEN DATA</span></header>
    <div className="wizard-viewport"><div className="wizard-track" style={{transform:`translateX(-${step*100}%)`}}>
      <section className="wizard-card welcome-card" aria-hidden={step!==0}><div className="wizard-six">6</div><div className="wizard-copy"><p className="wizard-kicker">RESTAURANT CLOSURE NAVIGATOR</p><h1>Six Days</h1><h2>Start with your restaurant.</h2><p>Understand the closure record, compare similar cases, see what changed at reopening, learn from repeat closures, and build a historical timeline.</p><div className="wizard-search"><label htmlFor="wizard-search">Find my restaurant</label><input id="wizard-search" placeholder="Restaurant name or CAMIS" value={query} onChange={e=>setQuery(e.target.value)} autoComplete="off"/>{matches.length>0&&<div className="wizard-matches">{matches.map(r=><button key={`${r.camis}-${r.closureDate}`} onClick={()=>choose(r)}><strong>{r.name}</strong><span>{r.borough} · CAMIS {r.camis}</span></button>)}</div>}</div><div className="or-line"><span>or</span></div><button className="sample-button" disabled={!sample} onClick={()=>sample&&choose(sample)}>Load sample restaurant <span>→</span></button></div></section>

      <Card step={1} current={step} eyebrow="01 · OFFICIAL CLOSURE RECORD" title="Why was this restaurant closed?" restaurant={restaurant}><div className="fact-grid"><Fact label="Action" value={restaurant?.action}/><Fact label="Inspection date" value={restaurant?.closureDate}/><Fact label="Score" value={restaurant?.score?.toString()??"Not recorded"}/><Fact label="Critical flags" value={restaurant?.criticalCount.toString()}/><Fact label="Inspection type" value={restaurant?.inspectionType}/></div><h3>Violation codes recorded at closure</h3><div className="wizard-codes">{restaurant?.codes.slice(0,6).map(v=><span key={v.code}><code>{v.code}</code>{v.description}</span>)}</div></Card>
      <Card step={2} current={step} eyebrow="02 · COMPARABLE CASES" title="What happened to restaurants like mine?" restaurant={restaurant}><div className="scope-switch"><button className={scope==="zip"?"active":""} onClick={()=>setScope("zip")}>ZIP {restaurant?.zipcode}</button><button className={scope==="borough"?"active":""} onClick={()=>setScope("borough")}>{restaurant?.borough}</button><button className={scope==="city"?"active":""} onClick={()=>setScope("city")}>All NYC</button></div><p className="result-sentence"><strong>{comparable.length}</strong> cases match geography, shared violations, similar burden, inspection type, and a two-year period.</p><div className="fact-grid"><Fact label="Matched reopenings" value={matchedDays.length.toString()}/><Fact label="Comparison median" value={med===null?"—":`${med} days`}/><Fact label="Still unmatched" value={(comparable.length-matchedDays.length).toString()}/><Fact label="Violation burden" value={`${Math.max(0,(restaurant?.codes.length??0)-2)}–${(restaurant?.codes.length??0)+2} codes`}/></div></Card>
      <Card step={3} current={step} eyebrow="03 · REOPENING CHANGES" title="Which violations disappeared, remained, or appeared?" restaurant={restaurant}><div className="change-columns"><article><span>DISAPPEARED</span><strong>{disappeared.length}</strong><p>{disappeared.map(v=>v.code).join(", ")||"None recorded"}</p></article><article><span>REMAINED</span><strong>{remained.length}</strong><p>{remained.map(v=>v.code).join(", ")||"None recorded"}</p></article><article><span>APPEARED</span><strong>{appeared.length}</strong><p>{appeared.map(v=>v.code).join(", ")||"None recorded"}</p></article></div><p className="data-boundary">Closure {restaurant?.closureDate} → reopening {restaurant?.reopeningDate??"not recorded"}. Absence from the next record does not prove a specific repair.</p></Card>
      <Card step={4} current={step} eyebrow="04 · REPEAT-CLOSURE PATTERNS" title="Which violations appeared again later?" restaurant={restaurant}><p className="result-sentence"><strong>{cohortRecurrence.length}</strong> recurring codes were observed after reopening within the retained comparison group.</p><div className="repeat-table">{cohortRecurrence.length?cohortRecurrence.map(([code,count])=><article key={code}><code>{code}</code><span>Present at closure and again in a later closure</span><strong>{count}</strong></article>):<p>No repeated closure-code pattern was available in this selected cohort.</p>}</div><p className="data-boundary">The analysis follows only comparable cases that reopened and later received another recorded closure.</p></Card>
      <Card step={5} current={step} eyebrow="05 · ACCUMULATED TIMELINE" title="How long did comparable cases take?" restaurant={restaurant}><div className="timeline-answer"><strong>{med??"—"}</strong><span>median recorded days<br/>among matched comparable cases</span></div><div className="thresholds">{[7,14,30].map(day=><article key={day}><strong>{pct(comparable.filter(b=>b.reopeningDays===null||b.reopeningDays>day).length,comparable.length)}</strong><span>without a recorded reopening by day {day}</span></article>)}</div><p className="data-boundary">Built from the restaurant, borough, violation match, reopening transition, and historical comparison carried through the earlier cards.</p></Card>
      <Card step={6} current={step} eyebrow="06 · LIVE RECORD" title="What has changed in my case?" restaurant={restaurant}><div className="fact-grid"><Fact label="Latest matched action" value={restaurant?.reopeningDate?"Reopened by DOHMH":restaurant?.action}/><Fact label="Latest matched date" value={restaurant?.reopeningDate??restaurant?.closureDate}/><Fact label="Later closures" value={restaurant?.laterClosureCount.toString()}/><Fact label="Data refreshed" value={fetchedAt}/></div><div className="watch-list">{["New inspection date or type","Changed closure or reopening action","New, repeated, or absent violation code","Grade or grade-date update","Later recorded closure"].map((x,i)=><span key={x}><b>{i+1}</b>{x}</span>)}</div><p className="data-boundary">Reloading Six Days compares the newest official rows with this accumulated case. The dataset is live public evidence, not an outcome prediction.</p></Card>
    </div></div>
    <footer className="wizard-footer"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Back</button><div>{step===0?<><strong>Begin the data journey</strong><span>Search above or use the sample restaurant</span></>:<><strong>{restaurant?.name}</strong><span>{restaurant?.codes.length} violations · {comparable.length} comparable cases · {med??"—"}-day median</span></>}</div>{step===0?<button className="next-card" disabled={!sample} onClick={()=>sample&&choose(sample)}>Load sample &amp; begin →</button>:step<6?<button className="next-card" onClick={()=>setStep(step+1)}>Next: {steps[step]} →</button>:<button className="next-card" onClick={restart}>Start again</button>}</footer>
  </main>
}

function Card({step,current,eyebrow,title,restaurant,children}:{step:number;current:number;eyebrow:string;title:string;restaurant:Restaurant|null;children:React.ReactNode}){return <section className="wizard-card data-card" aria-hidden={current!==step}><div className="card-shell"><div className="card-heading"><div><p className="wizard-kicker">{eyebrow}</p><h2>{title}</h2></div><span>{restaurant?.name}</span></div>{children}</div></section>}
function Fact({label,value}:{label:string;value?:string}){return <article><span>{label}</span><strong>{value??"—"}</strong></article>}
