"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { groupInspectionRows, matchCohort, recurrenceAnalysis, timelineAnalysis, type ClosureEpisode, type CohortFilters, type InspectionEvent, type RawInspectionRow } from "../lib/closure-analysis";
import type { BoroughMapPath } from "../lib/inspections";

const labels=["Closure","Compare","Reopening","Repeat closure","Timeline","Latest record"];
const stamp=new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"});
type Brief={data:string;analysis:string;learning:string;effect:string;next:string};
type FetchState="idle"|"loading"|"success"|"fallback";

const briefs:Record<number,Brief>={
  0:{data:"Your restaurant’s official action, inspection date, score, inspection type, violation codes, and critical flags.",analysis:"Build one closure profile from the official inspection record.",learning:"What did NYC Open Data record when my restaurant was closed?",effect:"The record helps you organize attention and resources around the problems officially documented in your case.",next:"Use this closure profile to find comparable NYC restaurants."},
  1:{data:"Shared violation codes, violation burden, inspection type, time period, and geography.",analysis:"Match your closure with similar NYC cases and retain one confirmed comparison group.",learning:"What happened to restaurants with closure records similar to mine?",effect:"A relevant comparison group provides more useful context than a single citywide average when evaluating your situation.",next:"Carry these exact restaurant IDs forward to examine their recorded reopenings."},
  2:{data:"Each retained restaurant’s closure record and its next recorded reopening event.",analysis:"Compare violation codes to identify which disappeared, remained, or appeared at reopening.",learning:"What changed in the public records of comparable restaurants before reopening was recorded?",effect:"Commonly remaining codes identify areas that may deserve closer review before your next inspection. The data does not reveal which repairs or services caused reopening.",next:"Follow the same reopened restaurants to determine which recorded problems appeared again."},
  3:{data:"The retained restaurants’ reopening records and later recorded closures during an observable 365-day period.",analysis:"Identify later closures and count which violation codes appeared again.",learning:"Which recorded problems recurred among comparable restaurants after reopening?",effect:"Recurring categories indicate areas that may warrant continued operational attention after reopening, but they do not predict that your restaurant will close again.",next:"Use the same retained cohort to calculate the historical reopening timeline."},
  4:{data:"Recorded closure and reopening dates for the retained comparison group.",analysis:"Calculate elapsed days, the median, the distribution, and the percentage without a recorded reopening at each eligible threshold.",learning:"How long did comparable cases historically take to receive a recorded reopening?",effect:"The observed range can inform cash-flow, staffing, inventory, supplier, and communications planning. It is not a predicted reopening date.",next:"Return to your restaurant and check its newest official NYC record."},
  5:{data:"The newest available NYC Open Data rows for the selected restaurant’s CAMIS identifier.",analysis:"Order the records by date and display the latest action, inspection, score, grade, and violation codes.",learning:"What does the public dataset currently show for my restaurant, and what has changed since the closure record?",effect:"The newest official evidence can help you identify what to verify next with DOHMH while retaining the comparison findings and historical timeline as context.",next:"This completes the chain. Restart the analysis to select another restaurant or refresh the available official record."},
};

export function OwnerWizard({episodes,events,boroughMap,fetchedAt}:{episodes:ClosureEpisode[];events:InspectionEvent[];boroughMap:BoroughMapPath[];fetchedAt:string}){
  const sample=useMemo(()=>episodes.find(e=>e.reopening&&e.closure.codes.length>=3&&matchCohort(e,episodes,{scope:"borough",burdenTolerance:2,periodYears:2,inspectionType:true,minSharedCodes:1}).length>=10)??episodes.find(e=>e.reopening&&e.closure.codes.length>=3)??episodes[0],[episodes]);
  const [selected,setSelected]=useState<ClosureEpisode|null>(null);
  const [step,setStep]=useState(0);
  const [query,setQuery]=useState("");
  const [filters,setFilters]=useState<CohortFilters>({scope:"borough",burdenTolerance:2,periodYears:2,inspectionType:true,minSharedCodes:1});
  const [retainedIds,setRetainedIds]=useState<string[]>([]);
  const [latestEvents,setLatestEvents]=useState<InspectionEvent[]>([]);
  const [fetchState,setFetchState]=useState<FetchState>("idle");
  const [retrievedAt,setRetrievedAt]=useState<Date|null>(null);
  const headingRefs=useRef<Array<HTMLHeadingElement|null>>([]);
  const matches=useMemo(()=>{const q=query.trim().toLowerCase();return q.length<2?[]:episodes.filter(e=>`${e.name} ${e.camis} ${e.address} ${e.zipcode}`.toLowerCase().includes(q)).slice(0,6)},[query,episodes]);
  const candidate=useMemo(()=>selected?matchCohort(selected,episodes,filters):[],[selected,episodes,filters]);
  const retained=useMemo(()=>{const ids=new Set(retainedIds);return episodes.filter(e=>ids.has(e.id))},[episodes,retainedIds]);
  const reopened=useMemo(()=>retained.filter(e=>e.reopening),[retained]);
  const recurrence=useMemo(()=>recurrenceAnalysis(retained,fetchedAt.slice(0,10)),[retained,fetchedAt]);
  const timeline=useMemo(()=>timelineAnalysis(retained,fetchedAt.slice(0,10)),[retained,fetchedAt]);
  const restaurantEvents=useMemo(()=>{const source=fetchState==="success"?latestEvents:events;return selected?source.filter(e=>e.camis===selected.camis).sort((a,b)=>b.date.localeCompare(a.date)):[]},[events,fetchState,latestEvents,selected]);
  const transitions=useMemo(()=>transitionRows(reopened),[reopened]);

  useEffect(()=>{if(step>0)headingRefs.current[step]?.focus()},[step]);
  useEffect(()=>{if(!selected)return;let cancelled=false;const params=new URLSearchParams({"$select":"camis,dba,boro,building,street,zipcode,inspection_date,inspection_type,action,violation_code,violation_description,critical_flag,score,grade,grade_date,record_date,latitude,longitude","$where":`camis='${selected.camis}'`,"$order":"inspection_date DESC","$limit":"50000"});fetch(`https://data.cityofnewyork.us/resource/43nn-pn8j.json?${params}`).then(r=>{if(!r.ok)throw new Error("Request failed");return r.json()}).then((rows:RawInspectionRow[])=>{if(cancelled)return;setLatestEvents(groupInspectionRows(rows));setRetrievedAt(new Date());setFetchState("success")}).catch(()=>{if(!cancelled){setRetrievedAt(new Date());setFetchState("fallback")}});return()=>{cancelled=true}},[selected]);

  const choose=(episode:ClosureEpisode)=>{setFetchState("loading");setLatestEvents([]);setRetrievedAt(null);setSelected(episode);setQuery(episode.name);setRetainedIds([]);setStep(0)};
  const next=()=>{if(step===0&&selected)setStep(1);else if(step===1){setRetainedIds(candidate.map(e=>e.id));setStep(2)}else if(step<5)setStep(step+1);else{setSelected(null);setQuery("");setRetainedIds([]);setStep(0)}};
  const canNext=step===0?!!selected:step===1?candidate.length>0:true;
  const nextLabel=step===0?"Compare this closure":step===1?`Retain these ${candidate.length} comparable cases`:step===2?"Follow reopened cases":step===3?"Build my timeline":step===4?"Check my latest record":"Start again";

  return <main className="wizard-page">
    <header className="wizard-header"><button className="wizard-brand" onClick={()=>setStep(0)}>Six Days</button><nav className="wizard-progress" aria-label="Analysis steps">{labels.map((label,i)=><button key={label} className={i===step?"active":i<step?"done":""} disabled={i>step||(!selected&&i>0)} onClick={()=>i<=step&&setStep(i)}><b>{i+1}</b><span>{label}</span></button>)}</nav><span className="live-dot"><i/> NYC OPEN DATA</span></header>
    <p className="sr-only" aria-live="polite">Step {step+1} of 6: {labels[step]}. {step>=2?`${retained.length} comparable closure episodes retained.`:""}</p>
    <div className="wizard-viewport"><div className="wizard-track" style={{transform:`translateX(-${step*100}%)`}}>
      <Stage current={step} index={0}><div className="page-one"><div className="finder-panel"><p className="wizard-kicker">NYC RESTAURANT CLOSURE NAVIGATOR</p><h1>Six Days</h1><h2>Find my restaurant.</h2><p>Start with one official closure record. Every comparison and calculation will follow from that evidence.</p><div className="wizard-search"><input aria-label="Restaurant name, CAMIS, address, or ZIP" placeholder="Name, CAMIS, address, or ZIP" value={query} onChange={e=>setQuery(e.target.value)}/>{matches.length>0&&query!==selected?.name&&<div className="wizard-matches">{matches.map(e=><button key={e.id} onClick={()=>choose(e)}><strong>{e.name}</strong><span>{e.address} · {e.closure.date} · CAMIS {e.camis}</span></button>)}</div>}</div><button className="sample-button" onClick={()=>sample&&choose(sample)}>Load sample restaurant <span>→</span></button></div>{selected?<ClosureRecord episode={selected} headingRef={el=>{headingRefs.current[0]=el}}/>:<div className="empty-record"><span>01</span><strong>Select a restaurant</strong><p>Its official closure evidence will appear here before you continue.</p></div>}</div></Stage>

      <Stage current={step} index={1}><CardShell kicker="02 · COMPARABLE CLOSURES" title="What happened to restaurants with closure records similar to mine?" headingRef={el=>{headingRefs.current[1]=el}} direct={`${candidate.length} NYC closure episodes match the current criteria; ${candidate.filter(e=>e.reopening).length} have a later recorded reopening.`}>
        <div className="compare-layout"><div className="compare-controls"><div className="scope-switch">{(["zip","borough","city"] as const).map(scope=><button key={scope} className={filters.scope===scope&&!filters.boroughOverride?"active":""} onClick={()=>setFilters({...filters,scope,boroughOverride:undefined})}>{scope==="zip"?`ZIP ${selected?.zipcode}`:scope==="borough"?selected?.borough:"All NYC"}</button>)}{filters.boroughOverride&&<button className="active">{filters.boroughOverride}</button>}</div><div className="filter-row"><label>Difference in recorded code count <input type="number" min="0" max="8" value={filters.burdenTolerance} onChange={e=>setFilters({...filters,burdenTolerance:Number(e.target.value)})}/></label><label>Period <select value={filters.periodYears} onChange={e=>setFilters({...filters,periodYears:Number(e.target.value)})}><option value="1">1 year</option><option value="2">2 years</option><option value="4">4 years</option></select></label><label><input type="checkbox" checked={filters.inspectionType} onChange={e=>setFilters({...filters,inspectionType:e.target.checked})}/> Same inspection type</label></div><MetricRow items={[["Candidate closures",candidate.length],["Later reopening matched",`${candidate.filter(e=>e.reopening).length} of ${candidate.length}`],["No later reopening matched",`${candidate.filter(e=>!e.reopening).length} of ${candidate.length}`]]}/><p className="criteria-copy">At least {filters.minSharedCodes} shared code · code-count difference within ±{filters.burdenTolerance} · {filters.inspectionType?"same inspection type":"any inspection type"} · {filters.periodYears}-year window · {filters.scope==="city"?"all NYC":filters.boroughOverride||filters.scope}</p>{candidate.length<30&&<p className="sample-warning">Small comparison group: widen geography or criteria before retaining these cases.</p>}</div><CohortMap paths={boroughMap} episodes={candidate} selected={selected} onBorough={borough=>setFilters({...filters,scope:"borough",boroughOverride:borough})}/></div>
        <BusinessMeaning>Historical context from records similar to yours is more useful than relying on one citywide average.</BusinessMeaning><HelpBrief brief={briefs[1]}/><Boundary>Similarity is defined only by the selected public-record fields. It does not establish identical operating conditions or corrective work. “No later reopening matched” does not prove that a restaurant never reopened.</Boundary>
      </CardShell></Stage>

      <Stage current={step} index={2}><CardShell kicker="03 · REOPENING CHANGES" title="What changed before comparable restaurants received a recorded reopening?" headingRef={el=>{headingRefs.current[2]=el}} direct={transitionAnswer(transitions,reopened.length)}><CohortRibbon retained={retained.length} reopened={reopened.length} eligible={recurrence.eligible} reclosed={recurrence.reclosed}/><TransitionCharts rows={transitions} matched={reopened.length}/><BusinessMeaning>Commonly remaining or newly recorded codes identify areas that may deserve closer review before the next inspection.</BusinessMeaning><HelpBrief brief={briefs[2]}/><Boundary>Code disappearance or persistence is an observed change between public records. It does not identify a repair or prove that a particular action or service caused reopening.</Boundary></CardShell></Stage>

      <Stage current={step} index={3}><CardShell kicker="04 · REPEAT-CLOSURE PATTERNS" title="Which recorded problems appeared again in later closures?" headingRef={el=>{headingRefs.current[3]=el}} direct={`${recurrence.reclosed} of ${recurrence.eligible} eligible reopened cases had another recorded closure within 365 days · ${recurrence.rate.toFixed(1)}%.`}><CohortRibbon retained={retained.length} reopened={reopened.length} eligible={recurrence.eligible} reclosed={recurrence.reclosed}/><div className="repeat-layout"><div className="repeat-rate"><strong>{recurrence.reclosed}<span> of {recurrence.eligible}</span></strong><p>eligible reopened cases had another recorded closure within 365 days</p><b>{recurrence.rate.toFixed(1)}%</b></div><RankedBars title="Codes recurring among reclosed cases" subtitle={`Denominator: ${recurrence.reclosed} cases with a later recorded closure`} rows={recurrence.codes.slice(0,7).map(r=>({code:r.code,description:codeDescription(retained,r.code),count:r.count,total:recurrence.reclosed}))}/></div>{recurrence.reclosed<20&&<p className="sample-warning strong-warning">Small sample: only {recurrence.reclosed} later closures contribute to the recurring-code percentages.</p>}<BusinessMeaning>Recurring categories show which documented issues appeared again historically and may warrant continued attention after reopening.</BusinessMeaning><HelpBrief brief={briefs[3]}/><Boundary>These are historical recurrence patterns among observable cases. They do not predict that the selected restaurant will close again.</Boundary></CardShell></Stage>

      <Stage current={step} index={4}><CardShell kicker="05 · HISTORICAL TIMELINE" title="How long did comparable cases historically take to receive a recorded reopening?" headingRef={el=>{headingRefs.current[4]=el}} direct={`The median recorded reopening interval was ${timeline.median??"not available"} days among ${timeline.matched} matched reopening records.`}><CohortRibbon retained={retained.length} reopened={reopened.length} eligible={recurrence.eligible} reclosed={recurrence.reclosed}/><TimelineChart values={timeline.values} median={timeline.median}/><div className="thresholds">{timeline.thresholds.map(t=><article key={t.days}><strong>{t.without} of {t.eligible}</strong><span>eligible cases had no recorded reopening by day {t.days}</span><b>{t.rate.toFixed(1)}%</b></article>)}</div><p className="eligibility-note">The eligible denominator changes because recent closures enter a threshold only after enough observable time has elapsed.</p><BusinessMeaning>The historical range can help you plan cash flow, staffing, inventory, suppliers, and communications. It is not a forecast.</BusinessMeaning><HelpBrief brief={briefs[4]}/><Boundary>These are historical public-record intervals, not a predicted reopening date. No matched action does not prove the restaurant remained operationally closed.</Boundary></CardShell></Stage>

      <Stage current={step} index={5}><CardShell kicker="06 · LATEST OFFICIAL RECORD" title="What does NYC Open Data currently show, and what changed since the selected closure?" headingRef={el=>{headingRefs.current[5]=el}} direct={latestAnswer(fetchState,restaurantEvents,selected)}><FetchStatus state={fetchState} retrievedAt={retrievedAt} snapshotAt={fetchedAt}/>{selected&&<LatestComparison closure={selected.closure} latest={restaurantEvents[0]}/>}<div className="latest-events"><h3>Official event history</h3>{restaurantEvents.slice(0,8).map(event=><article key={event.id}><time>{event.date}</time><div><strong>{event.action}</strong><span>{event.inspectionType} · {event.codes.length} recorded codes{event.grade?` · grade ${event.grade}`:""}</span></div></article>)}</div><BusinessMeaning>The newest available official evidence helps you identify what to verify with DOHMH while keeping the comparison analysis as historical context.</BusinessMeaning><HelpBrief brief={briefs[5]}/><Boundary>This is the latest available public record, not continuous monitoring or confirmation of current operating status. NYC Open Data may lag operational events and does not replace direct DOHMH communication.</Boundary></CardShell></Stage>
    </div></div>
    <footer className="wizard-footer"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Back</button><div><strong>{selected?.name??"Select a restaurant"}</strong><span>{step>=2?`${retained.length} comparison episodes retained unchanged`:(step===1?`${candidate.length} current candidates`:"Start with the official closure record")}</span></div><button className="next-card" disabled={!canNext} onClick={next}>{nextLabel} →</button></footer>
  </main>
}

function Stage({current,index,children}:{current:number;index:number;children:React.ReactNode}){return <section className="wizard-card" aria-hidden={current!==index} inert={current!==index}>{children}</section>}
function CardShell({kicker,title,direct,headingRef,children}:{kicker:string;title:string;direct:string;headingRef:(el:HTMLHeadingElement|null)=>void;children:React.ReactNode}){return <div className="card-shell"><header className="analysis-heading"><p className="wizard-kicker">{kicker}</p><h2 ref={headingRef} tabIndex={-1}>{title}</h2><p className="direct-answer">{direct}</p></header>{children}</div>}
function BusinessMeaning({children}:{children:React.ReactNode}){return <p className="business-meaning"><strong>What this means for your business</strong>{children}</p>}
function Boundary({children}:{children:React.ReactNode}){return <p className="data-boundary"><strong>Data boundary</strong>{children}</p>}
function HelpBrief({brief}:{brief:Brief}){return <details className="help-brief"><summary>How this analysis works</summary><dl>{[["Data",brief.data],["Analysis",brief.analysis],["You learn",brief.learning],["Business effect",brief.effect],["Next",brief.next]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details>}
function MetricRow({items}:{items:Array<[string,string|number]>}){return <div className="analysis-summary">{items.map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>}
function CohortRibbon({retained,reopened,eligible,reclosed}:{retained:number;reopened:number;eligible:number;reclosed:number}){return <div className="cohort-ribbon" aria-label="Comparison cohort flow"><strong>Comparison cohort</strong><span>{retained} retained</span><i>→</i><span>{reopened} matched reopenings</span><i>→</i><span>{eligible} eligible for 365 days</span><i>→</i><span>{reclosed} later closures</span></div>}
function ClosureRecord({episode,headingRef}:{episode:ClosureEpisode;headingRef:(el:HTMLHeadingElement|null)=>void}){const critical=episode.closure.codes.filter(c=>c.critical).length;return <article className="closure-panel"><header><p className="wizard-kicker">01 · CLOSURE RECORD</p><h2 ref={headingRef}>{episode.name}</h2><p>{episode.address} · {episode.borough} {episode.zipcode}</p><p className="direct-answer">NYC recorded this restaurant as closed on {episode.closure.date} with {episode.closure.codes.length} violation codes, including {critical} marked critical.</p></header><MetricRow items={[["Closure action",episode.closure.action],["Inspection date",episode.closure.date],["Inspection type",episode.closure.inspectionType],["Score",episode.closure.score??"Not recorded"],["Critical flags",critical],["Next matched action",episode.reopening?`Reopened ${episode.reopening.date}`:"No later reopening matched"]]}/><CodeTable codes={episode.closure.codes}/><BusinessMeaning>This record helps you organize attention around the issues officially documented in the closure inspection.</BusinessMeaning><HelpBrief brief={briefs[0]}/><Boundary>The public record documents the closure inspection. It does not independently prove which condition caused the closure or prescribe corrective services.</Boundary></article>}
function CodeTable({codes}:{codes:InspectionEvent["codes"]}){return <div className="code-table"><h3>Recorded violation codes · {codes.length}</h3><div className="code-table-head"><b>Code</b><b>NYC description</b><b>Flag</b></div>{codes.map(c=><div key={c.code}><code>{c.code}</code><span>{c.description}</span><b>{c.critical?"Critical":"Not critical"}</b></div>)}</div>}
function CohortMap({paths,episodes,selected,onBorough}:{paths:BoroughMapPath[];episodes:ClosureEpisode[];selected:ClosureEpisode|null;onBorough:(borough:string)=>void}){const counts=paths.map(p=>[p.name,episodes.filter(e=>e.borough===p.name).length] as const);return <figure className="cohort-map"><figcaption>Locations of all {episodes.length} current candidate closure episodes</figcaption><svg viewBox="0 0 720 430" role="img"><title>NYC comparable closure map</title><desc>Gold circles show all candidate closure episodes with coordinates. The larger outlined red marker shows the selected restaurant.</desc>{paths.map(path=><path key={path.name} d={path.path} fill="#ddd3c1" fillRule="evenodd" role="button" tabIndex={0} aria-label={`${path.name}: ${counts.find(c=>c[0]===path.name)?.[1]??0} candidates. Select borough.`} onClick={()=>onBorough(path.name)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" ")onBorough(path.name)}}/>)}{episodes.filter(e=>e.latitude!==null&&e.longitude!==null).map(e=><circle key={e.id} cx={(e.longitude!+74.26)/.56*720} cy={(40.92-e.latitude!)/.43*430} r="2.5"/>)}{selected&&selected.latitude!==null&&selected.longitude!==null&&<rect className="selected-dot" x={(selected.longitude+74.26)/.56*720-6} y={(40.92-selected.latitude)/.43*430-6} width="12" height="12"/>}</svg><div className="map-legend"><span><i/> Candidate closure</span><span><i className="selected"/> Selected restaurant</span></div><p className="map-summary">{counts.map(([name,count])=>`${name}: ${count}`).join(" · ")} · Missing coordinates: {episodes.filter(e=>e.latitude===null||e.longitude===null).length}</p></figure>}

type TransitionRow={code:string;description:string;atClosure:number;absent:number;remained:number;appeared:number};
function transitionRows(episodes:ClosureEpisode[]):TransitionRow[]{const rows=new Map<string,TransitionRow>();episodes.forEach(e=>{const before=new Map(e.closure.codes.map(c=>[c.code,c]));const after=new Map(e.reopening!.codes.map(c=>[c.code,c]));before.forEach((c,code)=>{const row=rows.get(code)??{code,description:c.description,atClosure:0,absent:0,remained:0,appeared:0};row.atClosure++;if(after.has(code))row.remained++;else row.absent++;rows.set(code,row)});after.forEach((c,code)=>{if(before.has(code))return;const row=rows.get(code)??{code,description:c.description,atClosure:0,absent:0,remained:0,appeared:0};row.appeared++;rows.set(code,row)})});return [...rows.values()].sort((a,b)=>(b.remained+b.appeared)-(a.remained+a.appeared))}
function transitionAnswer(rows:TransitionRow[],matched:number){const top=rows.filter(r=>r.remained>0).sort((a,b)=>b.remained-a.remained)[0];return top?`Among ${matched} matched reopening records, ${top.code} — ${top.description} — was the most commonly still-recorded closure code.`:`No still-recorded closure code was identified among ${matched} matched reopening records.`}
function TransitionCharts({rows,matched}:{rows:TransitionRow[];matched:number}){const closureRows=rows.filter(r=>r.atClosure>0).sort((a,b)=>b.remained-a.remained).slice(0,6);const appeared=rows.filter(r=>r.appeared>0).sort((a,b)=>b.appeared-a.appeared).slice(0,6);return <div className="transition-charts"><section><h3>Codes recorded at closure</h3><p>Each row uses only matched cases that contained that code at closure.</p>{closureRows.map(r=><article key={r.code}><header><code>{r.code}</code><span>{r.description}</span></header><div className="stacked-bar"><i style={{width:`${r.atClosure?r.absent/r.atClosure*100:0}%`}}/><b style={{width:`${r.atClosure?r.remained/r.atClosure*100:0}%`}}/></div><footer><span>No longer recorded: {r.absent} of {r.atClosure} · {pct(r.absent,r.atClosure)}</span><strong>Still recorded: {r.remained} of {r.atClosure} · {pct(r.remained,r.atClosure)}</strong></footer></article>)}</section><RankedBars title="Newly recorded at reopening" subtitle={`Denominator: ${matched} matched reopening records`} rows={appeared.map(r=>({code:r.code,description:r.description,count:r.appeared,total:matched}))}/></div>}
function RankedBars({title,subtitle,rows}:{title:string;subtitle:string;rows:Array<{code:string;description:string;count:number;total:number}>}){return <section className="ranked-bars"><h3>{title}</h3><p>{subtitle}</p>{rows.length?rows.map(r=><article key={r.code}><header><code>{r.code}</code><span>{r.description}</span></header><div><i style={{width:`${r.total?r.count/r.total*100:0}%`}}/></div><footer>{r.count} of {r.total} · {pct(r.count,r.total)}</footer></article>):<p className="empty-chart">No qualifying recorded codes.</p>}</section>}
function TimelineChart({values,median}:{values:number[];median:number|null}){const max=Math.max(30,...values);const points=values.length?[`0,100`,...values.map((v,i)=>`${v/max*100},${100-(i+1)/values.length*100}`)]:[];return <figure className="timeline-chart"><figcaption>Recorded reopening time among {values.length} matched cases</figcaption><div className="curve-wrap"><span className="y-label">% recorded reopened</span><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img"><title>Cumulative recorded reopening curve</title><desc>{values.length} matched reopening durations. Median {median??"unavailable"} days.</desc><line x1="0" y1="100" x2="100" y2="100"/><line x1="0" y1="0" x2="0" y2="100"/>{median!==null&&<line className="median-line" x1={median/max*100} y1="0" x2={median/max*100} y2="100"/>}<polyline points={points.join(" ")}/></svg><div className="x-labels"><span>0</span><span>7</span><span>14</span><span>30</span><span>{max} days</span></div></div><p>Median reference: {median??"not available"} days. The curve includes only cases with a matched recorded reopening.</p></figure>}
function FetchStatus({state,retrievedAt,snapshotAt}:{state:FetchState;retrievedAt:Date|null;snapshotAt:string}){return <p className={`fetch-status ${state}`} aria-live="polite">{state==="loading"?"Checking NYC Open Data…":state==="success"?`Latest available public record retrieved ${retrievedAt?stamp.format(retrievedAt):"now"}.`:state==="fallback"?`Request failed—showing the saved dataset snapshot from ${stamp.format(new Date(snapshotAt))}.`:"Select a restaurant to check its latest available record."}</p>}
function latestAnswer(state:FetchState,events:InspectionEvent[],selected:ClosureEpisode|null){if(state==="loading")return "Checking NYC Open Data for the newest available public record.";const latest=events[0];if(!selected||!latest)return "No official record is available for comparison.";if(latest.date<=selected.closure.date)return `No newer official record was found after the selected closure on ${selected.closure.date}.`;return `The latest available record is dated ${latest.date}: ${latest.action}`}
function LatestComparison({closure,latest}:{closure:InspectionEvent;latest?:InspectionEvent}){if(!latest)return <p className="empty-chart">No latest record is available for comparison.</p>;const before=new Map(closure.codes.map(c=>[c.code,c]));const after=new Map(latest.codes.map(c=>[c.code,c]));const removed=[...before.values()].filter(c=>!after.has(c.code));const still=[...before.values()].filter(c=>after.has(c.code));const appeared=[...after.values()].filter(c=>!before.has(c.code));return <div className="latest-comparison"><div className="comparison-table"><div><b>Field</b><b>Selected closure</b><b>Latest available record</b></div>{[["Inspection date",closure.date,latest.date],["Action",closure.action,latest.action],["Inspection type",closure.inspectionType,latest.inspectionType],["Score",closure.score??"Not recorded",latest.score??"Not recorded"],["Grade",closure.grade??"Not recorded",latest.grade??"Not recorded"]].map(row=><div key={String(row[0])}><strong>{row[0]}</strong><span>{row[1]}</span><span>{row[2]}</span></div>)}</div><div className="code-changes">{[["No longer recorded",removed],["Still recorded",still],["Newly recorded",appeared]].map(([label,codes])=><section key={String(label)}><h3>{label as string}</h3>{(codes as InspectionEvent["codes"]).length?(codes as InspectionEvent["codes"]).map(c=><p key={c.code}><code>{c.code}</code>{c.description}</p>):<p>None in this comparison.</p>}</section>)}</div></div>}
function codeDescription(episodes:ClosureEpisode[],code:string){for(const e of episodes){const found=[...e.closure.codes,...(e.reopening?.codes??[]),...(e.laterClosure?.codes??[])].find(c=>c.code===code);if(found)return found.description}return "Recorded violation"}
function pct(n:number,d:number){return d?`${(n/d*100).toFixed(1)}%`:"—"}
